/* Constants.c generated by valac 0.40.11, the Vala compiler
 * generated from Constants.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define APP_CONFIGS_TYPE_CONSTANTS (app_configs_constants_get_type ())
#define APP_CONFIGS_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CONFIGS_TYPE_CONSTANTS, AppConfigsConstants))
#define APP_CONFIGS_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CONFIGS_TYPE_CONSTANTS, AppConfigsConstantsClass))
#define APP_CONFIGS_IS_CONSTANTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CONFIGS_TYPE_CONSTANTS))
#define APP_CONFIGS_IS_CONSTANTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CONFIGS_TYPE_CONSTANTS))
#define APP_CONFIGS_CONSTANTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CONFIGS_TYPE_CONSTANTS, AppConfigsConstantsClass))

typedef struct _AppConfigsConstants AppConfigsConstants;
typedef struct _AppConfigsConstantsClass AppConfigsConstantsClass;
typedef struct _AppConfigsConstantsPrivate AppConfigsConstantsPrivate;
typedef struct _AppConfigsParamSpecConstants AppConfigsParamSpecConstants;

struct _AppConfigsConstants {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AppConfigsConstantsPrivate * priv;
};

struct _AppConfigsConstantsClass {
	GTypeClass parent_class;
	void (*finalize) (AppConfigsConstants *self);
};

struct _AppConfigsParamSpecConstants {
	GParamSpec parent_instance;
};


static gpointer app_configs_constants_parent_class = NULL;

gpointer app_configs_constants_ref (gpointer instance);
void app_configs_constants_unref (gpointer instance);
GParamSpec* app_configs_param_spec_constants (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void app_configs_value_set_constants (GValue* value,
                                      gpointer v_object);
void app_configs_value_take_constants (GValue* value,
                                       gpointer v_object);
gpointer app_configs_value_get_constants (const GValue* value);
GType app_configs_constants_get_type (void) G_GNUC_CONST;
#define APP_CONFIGS_CONSTANTS_ID "com.github.calo001.luna"
#define APP_CONFIGS_CONSTANTS_APP_ICON "com.github.calo001.luna"
#define APP_CONFIGS_CONSTANTS_STACK_CALENDAR "calendar"
#define APP_CONFIGS_CONSTANTS_STACK_YEARS "years"
#define APP_CONFIGS_CONSTANTS_STACK_MONTHS "months"
#define APP_CONFIGS_CONSTANTS_ICON_SUMMER "/com/github/calo001/luna/images/summer.svg"
#define APP_CONFIGS_CONSTANTS_ICON_SPRING "/com/github/calo001/luna/images/spring.svg"
#define APP_CONFIGS_CONSTANTS_ICON_AUTOMN "/com/github/calo001/luna/images/autumn.svg"
#define APP_CONFIGS_CONSTANTS_ICON_WINTER "/com/github/calo001/luna/images/winter.svg"
#define APP_CONFIGS_CONSTANTS_URL_CSS_WHITE "/com/github/calo001/luna/css/style_white.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK "/com/github/calo001/luna/css/style_dark.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PINK "/com/github/calo001/luna/css/style_pink.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_RED "/com/github/calo001/luna/css/style_red.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_ORANGE "/com/github/calo001/luna/css/style_orange.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_YELLOW "/com/github/calo001/luna/css/style_yellow.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GREEN "/com/github/calo001/luna/css/style_green.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_TEAL "/com/github/calo001/luna/css/style_teal.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_BLUE "/com/github/calo001/luna/css/style_blue.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PURPLE "/com/github/calo001/luna/css/style_purple.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_COCO "/com/github/calo001/luna/css/style_coco.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_BLUE_GREEN "/com/github/calo001/luna/css/style_gradient_blue_green.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_PURPLE_RED "/com/github/calo001/luna/css/style_gradient_purple_red.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PRIDE "/com/github/calo001/luna/css/style_gradient_pride.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_TRANS "/com/github/calo001/luna/css/style_light_transparent.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK_TRANS "/com/github/calo001/luna/css/style_dark_transparent.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_SEMITRANS "/com/github/calo001/luna/css/style_light_semitrans.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK_SEMITRANS "/com/github/calo001/luna/css/style_dark_semitrans.css"
AppConfigsConstants* app_configs_constants_new (void);
AppConfigsConstants* app_configs_constants_construct (GType object_type);
static void app_configs_constants_finalize (AppConfigsConstants * obj);


AppConfigsConstants*
app_configs_constants_construct (GType object_type)
{
	AppConfigsConstants* self = NULL;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	self = (AppConfigsConstants*) g_type_create_instance (object_type);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return self;
#line 114 "Constants.c"
}


AppConfigsConstants*
app_configs_constants_new (void)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return app_configs_constants_construct (APP_CONFIGS_TYPE_CONSTANTS);
#line 123 "Constants.c"
}


static void
app_configs_value_constants_init (GValue* value)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	value->data[0].v_pointer = NULL;
#line 132 "Constants.c"
}


static void
app_configs_value_constants_free_value (GValue* value)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (value->data[0].v_pointer) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		app_configs_constants_unref (value->data[0].v_pointer);
#line 143 "Constants.c"
	}
}


static void
app_configs_value_constants_copy_value (const GValue* src_value,
                                        GValue* dest_value)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (src_value->data[0].v_pointer) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		dest_value->data[0].v_pointer = app_configs_constants_ref (src_value->data[0].v_pointer);
#line 156 "Constants.c"
	} else {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		dest_value->data[0].v_pointer = NULL;
#line 160 "Constants.c"
	}
}


static gpointer
app_configs_value_constants_peek_pointer (const GValue* value)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return value->data[0].v_pointer;
#line 170 "Constants.c"
}


static gchar*
app_configs_value_constants_collect_value (GValue* value,
                                           guint n_collect_values,
                                           GTypeCValue* collect_values,
                                           guint collect_flags)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (collect_values[0].v_pointer) {
#line 182 "Constants.c"
		AppConfigsConstants * object;
		object = collect_values[0].v_pointer;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		if (object->parent_instance.g_class == NULL) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 189 "Constants.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 193 "Constants.c"
		}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = app_configs_constants_ref (object);
#line 197 "Constants.c"
	} else {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = NULL;
#line 201 "Constants.c"
	}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return NULL;
#line 205 "Constants.c"
}


static gchar*
app_configs_value_constants_lcopy_value (const GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
	AppConfigsConstants ** object_p;
	object_p = collect_values[0].v_pointer;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (!object_p) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 221 "Constants.c"
	}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (!value->data[0].v_pointer) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		*object_p = NULL;
#line 227 "Constants.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		*object_p = value->data[0].v_pointer;
#line 231 "Constants.c"
	} else {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		*object_p = app_configs_constants_ref (value->data[0].v_pointer);
#line 235 "Constants.c"
	}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return NULL;
#line 239 "Constants.c"
}


GParamSpec*
app_configs_param_spec_constants (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags)
{
	AppConfigsParamSpecConstants* spec;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_return_val_if_fail (g_type_is_a (object_type, APP_CONFIGS_TYPE_CONSTANTS), NULL);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return G_PARAM_SPEC (spec);
#line 259 "Constants.c"
}


gpointer
app_configs_value_get_constants (const GValue* value)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_CONSTANTS), NULL);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return value->data[0].v_pointer;
#line 270 "Constants.c"
}


void
app_configs_value_set_constants (GValue* value,
                                 gpointer v_object)
{
	AppConfigsConstants * old;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_CONSTANTS));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	old = value->data[0].v_pointer;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (v_object) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONFIGS_TYPE_CONSTANTS));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = v_object;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		app_configs_constants_ref (value->data[0].v_pointer);
#line 293 "Constants.c"
	} else {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = NULL;
#line 297 "Constants.c"
	}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (old) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		app_configs_constants_unref (old);
#line 303 "Constants.c"
	}
}


void
app_configs_value_take_constants (GValue* value,
                                  gpointer v_object)
{
	AppConfigsConstants * old;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_CONSTANTS));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	old = value->data[0].v_pointer;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (v_object) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONFIGS_TYPE_CONSTANTS));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = v_object;
#line 325 "Constants.c"
	} else {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		value->data[0].v_pointer = NULL;
#line 329 "Constants.c"
	}
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (old) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		app_configs_constants_unref (old);
#line 335 "Constants.c"
	}
}


static void
app_configs_constants_class_init (AppConfigsConstantsClass * klass)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	app_configs_constants_parent_class = g_type_class_peek_parent (klass);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	((AppConfigsConstantsClass *) klass)->finalize = app_configs_constants_finalize;
#line 347 "Constants.c"
}


static void
app_configs_constants_instance_init (AppConfigsConstants * self)
{
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	self->ref_count = 1;
#line 356 "Constants.c"
}


static void
app_configs_constants_finalize (AppConfigsConstants * obj)
{
	AppConfigsConstants * self;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CONFIGS_TYPE_CONSTANTS, AppConfigsConstants);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_signal_handlers_destroy (self);
#line 368 "Constants.c"
}


/**
     * The {@code Constants} class is responsible for defining all 
     * the constants used in the application.
     *
     * @since 1.0.0
     */
GType
app_configs_constants_get_type (void)
{
	static volatile gsize app_configs_constants_type_id__volatile = 0;
	if (g_once_init_enter (&app_configs_constants_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { app_configs_value_constants_init, app_configs_value_constants_free_value, app_configs_value_constants_copy_value, app_configs_value_constants_peek_pointer, "p", app_configs_value_constants_collect_value, "p", app_configs_value_constants_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (AppConfigsConstantsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_configs_constants_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppConfigsConstants), 0, (GInstanceInitFunc) app_configs_constants_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType app_configs_constants_type_id;
		app_configs_constants_type_id = g_type_register_fundamental (g_type_fundamental_next (), "AppConfigsConstants", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&app_configs_constants_type_id__volatile, app_configs_constants_type_id);
	}
	return app_configs_constants_type_id__volatile;
}


gpointer
app_configs_constants_ref (gpointer instance)
{
	AppConfigsConstants * self;
	self = instance;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	g_atomic_int_inc (&self->ref_count);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	return instance;
#line 403 "Constants.c"
}


void
app_configs_constants_unref (gpointer instance)
{
	AppConfigsConstants * self;
	self = instance;
#line 30 "/run/build/Luna/src/configs/Constants.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		APP_CONFIGS_CONSTANTS_GET_CLASS (self)->finalize (self);
#line 30 "/run/build/Luna/src/configs/Constants.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 418 "Constants.c"
	}
}



