/* Settings.c generated by valac 0.40.11, the Vala compiler
 * generated from Settings.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <stdlib.h>
#include <string.h>


#define APP_CONFIGS_TYPE_SETTINGS (app_configs_settings_get_type ())
#define APP_CONFIGS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettings))
#define APP_CONFIGS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettingsClass))
#define APP_CONFIGS_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CONFIGS_TYPE_SETTINGS))
#define APP_CONFIGS_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CONFIGS_TYPE_SETTINGS))
#define APP_CONFIGS_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettingsClass))

typedef struct _AppConfigsSettings AppConfigsSettings;
typedef struct _AppConfigsSettingsClass AppConfigsSettingsClass;
typedef struct _AppConfigsSettingsPrivate AppConfigsSettingsPrivate;
enum  {
	APP_CONFIGS_SETTINGS_0_PROPERTY,
	APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY,
	APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY,
	APP_CONFIGS_SETTINGS_COLOR_PROPERTY,
	APP_CONFIGS_SETTINGS_NUM_PROPERTIES
};
static GParamSpec* app_configs_settings_properties[APP_CONFIGS_SETTINGS_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _AppConfigsSettings {
	GraniteServicesSettings parent_instance;
	AppConfigsSettingsPrivate * priv;
};

struct _AppConfigsSettingsClass {
	GraniteServicesSettingsClass parent_class;
};

struct _AppConfigsSettingsPrivate {
	gint _window_x;
	gint _window_y;
	gchar* _color;
};


static gpointer app_configs_settings_parent_class = NULL;
static AppConfigsSettings* app_configs_settings_instance;
static AppConfigsSettings* app_configs_settings_instance = NULL;

GType app_configs_settings_get_type (void) G_GNUC_CONST;
#define APP_CONFIGS_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettingsPrivate))
static AppConfigsSettings* app_configs_settings_new (void);
static AppConfigsSettings* app_configs_settings_construct (GType object_type);
#define APP_CONFIGS_CONSTANTS_ID "com.github.calo001.luna"
AppConfigsSettings* app_configs_settings_get_instance (void);
gint app_configs_settings_get_window_x (AppConfigsSettings* self);
void app_configs_settings_set_window_x (AppConfigsSettings* self,
                                        gint value);
gint app_configs_settings_get_window_y (AppConfigsSettings* self);
void app_configs_settings_set_window_y (AppConfigsSettings* self,
                                        gint value);
const gchar* app_configs_settings_get_color (AppConfigsSettings* self);
void app_configs_settings_set_color (AppConfigsSettings* self,
                                     const gchar* value);
static void app_configs_settings_finalize (GObject * obj);
static void _vala_app_configs_settings_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec);
static void _vala_app_configs_settings_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec);


/**
         * Constructs a new {@code Settings} object 
         * and sets the default exit folder.
         */
static AppConfigsSettings*
app_configs_settings_construct (GType object_type)
{
	AppConfigsSettings * self = NULL;
#line 58 "/run/build/Luna/src/configs/Settings.vala"
	self = (AppConfigsSettings*) granite_services_settings_construct (object_type, APP_CONFIGS_CONSTANTS_ID);
#line 57 "/run/build/Luna/src/configs/Settings.vala"
	return self;
#line 110 "Settings.c"
}


static AppConfigsSettings*
app_configs_settings_new (void)
{
#line 57 "/run/build/Luna/src/configs/Settings.vala"
	return app_configs_settings_construct (APP_CONFIGS_TYPE_SETTINGS);
#line 119 "Settings.c"
}


/**
         * Returns a single instance of this class.
         * 
         * @return {@code Settings}
         */
AppConfigsSettings*
app_configs_settings_get_instance (void)
{
	AppConfigsSettings* result = NULL;
	AppConfigsSettings* _tmp0_;
	AppConfigsSettings* _tmp2_;
#line 67 "/run/build/Luna/src/configs/Settings.vala"
	_tmp0_ = app_configs_settings_instance;
#line 67 "/run/build/Luna/src/configs/Settings.vala"
	if (_tmp0_ == NULL) {
#line 138 "Settings.c"
		AppConfigsSettings* _tmp1_;
#line 68 "/run/build/Luna/src/configs/Settings.vala"
		_tmp1_ = app_configs_settings_new ();
#line 68 "/run/build/Luna/src/configs/Settings.vala"
		_g_object_unref0 (app_configs_settings_instance);
#line 68 "/run/build/Luna/src/configs/Settings.vala"
		app_configs_settings_instance = _tmp1_;
#line 146 "Settings.c"
	}
#line 71 "/run/build/Luna/src/configs/Settings.vala"
	_tmp2_ = app_configs_settings_instance;
#line 71 "/run/build/Luna/src/configs/Settings.vala"
	result = _tmp2_;
#line 71 "/run/build/Luna/src/configs/Settings.vala"
	return result;
#line 154 "Settings.c"
}


gint
app_configs_settings_get_window_x (AppConfigsSettings* self)
{
	gint result;
	gint _tmp0_;
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	_tmp0_ = self->priv->_window_x;
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	result = _tmp0_;
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	return result;
#line 171 "Settings.c"
}


void
app_configs_settings_set_window_x (AppConfigsSettings* self,
                                   gint value)
{
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	g_return_if_fail (self != NULL);
#line 39 "/run/build/Luna/src/configs/Settings.vala"
	if (app_configs_settings_get_window_x (self) != value) {
#line 39 "/run/build/Luna/src/configs/Settings.vala"
		self->priv->_window_x = value;
#line 39 "/run/build/Luna/src/configs/Settings.vala"
		g_object_notify_by_pspec ((GObject *) self, app_configs_settings_properties[APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY]);
#line 187 "Settings.c"
	}
}


gint
app_configs_settings_get_window_y (AppConfigsSettings* self)
{
	gint result;
	gint _tmp0_;
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	_tmp0_ = self->priv->_window_y;
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	result = _tmp0_;
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	return result;
#line 205 "Settings.c"
}


void
app_configs_settings_set_window_y (AppConfigsSettings* self,
                                   gint value)
{
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	g_return_if_fail (self != NULL);
#line 45 "/run/build/Luna/src/configs/Settings.vala"
	if (app_configs_settings_get_window_y (self) != value) {
#line 45 "/run/build/Luna/src/configs/Settings.vala"
		self->priv->_window_y = value;
#line 45 "/run/build/Luna/src/configs/Settings.vala"
		g_object_notify_by_pspec ((GObject *) self, app_configs_settings_properties[APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY]);
#line 221 "Settings.c"
	}
}


const gchar*
app_configs_settings_get_color (AppConfigsSettings* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	_tmp0_ = self->priv->_color;
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	result = _tmp0_;
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	return result;
#line 239 "Settings.c"
}


void
app_configs_settings_set_color (AppConfigsSettings* self,
                                const gchar* value)
{
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	g_return_if_fail (self != NULL);
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	if (g_strcmp0 (value, app_configs_settings_get_color (self)) != 0) {
#line 251 "Settings.c"
		gchar* _tmp0_;
#line 51 "/run/build/Luna/src/configs/Settings.vala"
		_tmp0_ = g_strdup (value);
#line 51 "/run/build/Luna/src/configs/Settings.vala"
		_g_free0 (self->priv->_color);
#line 51 "/run/build/Luna/src/configs/Settings.vala"
		self->priv->_color = _tmp0_;
#line 51 "/run/build/Luna/src/configs/Settings.vala"
		g_object_notify_by_pspec ((GObject *) self, app_configs_settings_properties[APP_CONFIGS_SETTINGS_COLOR_PROPERTY]);
#line 261 "Settings.c"
	}
}


static void
app_configs_settings_class_init (AppConfigsSettingsClass * klass)
{
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	app_configs_settings_parent_class = g_type_class_peek_parent (klass);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	g_type_class_add_private (klass, sizeof (AppConfigsSettingsPrivate));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_app_configs_settings_get_property;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_app_configs_settings_set_property;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	G_OBJECT_CLASS (klass)->finalize = app_configs_settings_finalize;
#line 279 "Settings.c"
	/**
	         * This property will represent the location x of the screen.
	         * Variable of type {@code int} as declared.
	         */
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY, app_configs_settings_properties[APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY] = g_param_spec_int ("window-x", "window-x", "window-x", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 286 "Settings.c"
	/**
	         * This property will represent the location y of the screen.
	         * Variable of type {@code int} as declared.
	         */
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY, app_configs_settings_properties[APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY] = g_param_spec_int ("window-y", "window-y", "window-y", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 293 "Settings.c"
	/**
	         * This property will represent the color of window
	         * Variable of type {@code string} as declared.
	         */
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_CONFIGS_SETTINGS_COLOR_PROPERTY, app_configs_settings_properties[APP_CONFIGS_SETTINGS_COLOR_PROPERTY] = g_param_spec_string ("color", "color", "color", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 300 "Settings.c"
}


static void
app_configs_settings_instance_init (AppConfigsSettings * self)
{
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	self->priv = APP_CONFIGS_SETTINGS_GET_PRIVATE (self);
#line 309 "Settings.c"
}


static void
app_configs_settings_finalize (GObject * obj)
{
	AppConfigsSettings * self;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettings);
#line 51 "/run/build/Luna/src/configs/Settings.vala"
	_g_free0 (self->priv->_color);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	G_OBJECT_CLASS (app_configs_settings_parent_class)->finalize (obj);
#line 323 "Settings.c"
}


/**
     * The {@code Settings} class is responsible for defining all 
     * the texts that are displayed in the application and must be translated.
     *
     * @see Granite.Services.Settings
     * @since 1.0.0
     */
GType
app_configs_settings_get_type (void)
{
	static volatile gsize app_configs_settings_type_id__volatile = 0;
	if (g_once_init_enter (&app_configs_settings_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppConfigsSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_configs_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppConfigsSettings), 0, (GInstanceInitFunc) app_configs_settings_instance_init, NULL };
		GType app_configs_settings_type_id;
		app_configs_settings_type_id = g_type_register_static (GRANITE_SERVICES_TYPE_SETTINGS, "AppConfigsSettings", &g_define_type_info, 0);
		g_once_init_leave (&app_configs_settings_type_id__volatile, app_configs_settings_type_id);
	}
	return app_configs_settings_type_id__volatile;
}


static void
_vala_app_configs_settings_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec)
{
	AppConfigsSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettings);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	switch (property_id) {
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		g_value_set_int (value, app_configs_settings_get_window_x (self));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		g_value_set_int (value, app_configs_settings_get_window_y (self));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_COLOR_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		g_value_set_string (value, app_configs_settings_get_color (self));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 376 "Settings.c"
		default:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 382 "Settings.c"
	}
}


static void
_vala_app_configs_settings_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec)
{
	AppConfigsSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettings);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
	switch (property_id) {
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_WINDOW_X_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		app_configs_settings_set_window_x (self, g_value_get_int (value));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_WINDOW_Y_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		app_configs_settings_set_window_y (self, g_value_get_int (value));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		case APP_CONFIGS_SETTINGS_COLOR_PROPERTY:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		app_configs_settings_set_color (self, g_value_get_string (value));
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 415 "Settings.c"
		default:
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/run/build/Luna/src/configs/Settings.vala"
		break;
#line 421 "Settings.c"
	}
}



