/* Strings.c generated by valac 0.40.11, the Vala compiler
 * generated from Strings.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gobject/gvaluecollector.h>


#define APP_CONFIGS_TYPE_S (app_configs_s_get_type ())
#define APP_CONFIGS_S(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CONFIGS_TYPE_S, AppConfigsS))
#define APP_CONFIGS_S_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CONFIGS_TYPE_S, AppConfigsSClass))
#define APP_CONFIGS_IS_S(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CONFIGS_TYPE_S))
#define APP_CONFIGS_IS_S_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CONFIGS_TYPE_S))
#define APP_CONFIGS_S_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CONFIGS_TYPE_S, AppConfigsSClass))

typedef struct _AppConfigsS AppConfigsS;
typedef struct _AppConfigsSClass AppConfigsSClass;
typedef struct _AppConfigsSPrivate AppConfigsSPrivate;
typedef struct _AppConfigsParamSpecS AppConfigsParamSpecS;

struct _AppConfigsS {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AppConfigsSPrivate * priv;
};

struct _AppConfigsSClass {
	GTypeClass parent_class;
	void (*finalize) (AppConfigsS *self);
};

struct _AppConfigsParamSpecS {
	GParamSpec parent_instance;
};


static gpointer app_configs_s_parent_class = NULL;

gpointer app_configs_s_ref (gpointer instance);
void app_configs_s_unref (gpointer instance);
GParamSpec* app_configs_param_spec_s (const gchar* name,
                                      const gchar* nick,
                                      const gchar* blurb,
                                      GType object_type,
                                      GParamFlags flags);
void app_configs_value_set_s (GValue* value,
                              gpointer v_object);
void app_configs_value_take_s (GValue* value,
                               gpointer v_object);
gpointer app_configs_value_get_s (const GValue* value);
GType app_configs_s_get_type (void) G_GNUC_CONST;
#define APP_CONFIGS_S_MONDAY _ ("MON")
#define APP_CONFIGS_S_TUESDAY _ ("TUE")
#define APP_CONFIGS_S_WEDNESDAY _ ("WED")
#define APP_CONFIGS_S_THURSDAY _ ("THU")
#define APP_CONFIGS_S_FRIDAY _ ("FRI")
#define APP_CONFIGS_S_SATURDAT _ ("SAT")
#define APP_CONFIGS_S_SUNDAY _ ("SUN")
#define APP_CONFIGS_S_JANUARY _ ("January")
#define APP_CONFIGS_S_FEBRUARY _ ("February")
#define APP_CONFIGS_S_MARCH _ ("March")
#define APP_CONFIGS_S_APRIL _ ("April")
#define APP_CONFIGS_S_MAY _ ("May")
#define APP_CONFIGS_S_JUNE _ ("June")
#define APP_CONFIGS_S_JULY _ ("July")
#define APP_CONFIGS_S_AUGUST _ ("August")
#define APP_CONFIGS_S_SEPTEMBER _ ("September")
#define APP_CONFIGS_S_OCTOBER _ ("October")
#define APP_CONFIGS_S_NOVEMBER _ ("November")
#define APP_CONFIGS_S_DECEMBER _ ("December")
#define APP_CONFIGS_S_GO_TODAY _ ("GO TODAY")
#define APP_CONFIGS_S_SELECT_THEME_COLOR _ ("Select a theme color")
#define APP_CONFIGS_S_WHITE _ ("White")
#define APP_CONFIGS_S_BLACK _ ("Black")
#define APP_CONFIGS_S_PINK _ ("Pink")
#define APP_CONFIGS_S_RED _ ("Red")
#define APP_CONFIGS_S_ORANGE _ ("Orange")
#define APP_CONFIGS_S_GREEN _ ("Green")
#define APP_CONFIGS_S_TEAL _ ("Teal")
#define APP_CONFIGS_S_YELLOW _ ("Yellow")
#define APP_CONFIGS_S_BLUE _ ("Blue")
#define APP_CONFIGS_S_PURPLE _ ("Purple")
#define APP_CONFIGS_S_COCO _ ("Coco")
#define APP_CONFIGS_S_BLUE_TO_GREEEN _ ("Blue to Green")
#define APP_CONFIGS_S_PURPLE_TO_RED _ ("Purple to Red")
#define APP_CONFIGS_S_PRIDE _ ("Pride")
#define APP_CONFIGS_S_TRANSPARENT_BLACK _ ("Transparent black")
#define APP_CONFIGS_S_TRANSPARENT_WHITE _ ("Transparent white")
#define APP_CONFIGS_S_SEMITRANSPARENT_BLACK _ ("Semi Transparent black")
#define APP_CONFIGS_S_SEMITRANSPARENT_WHITE _ ("Semi Transparent white")
AppConfigsS* app_configs_s_new (void);
AppConfigsS* app_configs_s_construct (GType object_type);
static void app_configs_s_finalize (AppConfigsS * obj);


AppConfigsS*
app_configs_s_construct (GType object_type)
{
	AppConfigsS* self = NULL;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	self = (AppConfigsS*) g_type_create_instance (object_type);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return self;
#line 127 "Strings.c"
}


AppConfigsS*
app_configs_s_new (void)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return app_configs_s_construct (APP_CONFIGS_TYPE_S);
#line 136 "Strings.c"
}


static void
app_configs_value_s_init (GValue* value)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	value->data[0].v_pointer = NULL;
#line 145 "Strings.c"
}


static void
app_configs_value_s_free_value (GValue* value)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (value->data[0].v_pointer) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		app_configs_s_unref (value->data[0].v_pointer);
#line 156 "Strings.c"
	}
}


static void
app_configs_value_s_copy_value (const GValue* src_value,
                                GValue* dest_value)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (src_value->data[0].v_pointer) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		dest_value->data[0].v_pointer = app_configs_s_ref (src_value->data[0].v_pointer);
#line 169 "Strings.c"
	} else {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		dest_value->data[0].v_pointer = NULL;
#line 173 "Strings.c"
	}
}


static gpointer
app_configs_value_s_peek_pointer (const GValue* value)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return value->data[0].v_pointer;
#line 183 "Strings.c"
}


static gchar*
app_configs_value_s_collect_value (GValue* value,
                                   guint n_collect_values,
                                   GTypeCValue* collect_values,
                                   guint collect_flags)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (collect_values[0].v_pointer) {
#line 195 "Strings.c"
		AppConfigsS * object;
		object = collect_values[0].v_pointer;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		if (object->parent_instance.g_class == NULL) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 202 "Strings.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 206 "Strings.c"
		}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = app_configs_s_ref (object);
#line 210 "Strings.c"
	} else {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = NULL;
#line 214 "Strings.c"
	}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return NULL;
#line 218 "Strings.c"
}


static gchar*
app_configs_value_s_lcopy_value (const GValue* value,
                                 guint n_collect_values,
                                 GTypeCValue* collect_values,
                                 guint collect_flags)
{
	AppConfigsS ** object_p;
	object_p = collect_values[0].v_pointer;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (!object_p) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 234 "Strings.c"
	}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (!value->data[0].v_pointer) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		*object_p = NULL;
#line 240 "Strings.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		*object_p = value->data[0].v_pointer;
#line 244 "Strings.c"
	} else {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		*object_p = app_configs_s_ref (value->data[0].v_pointer);
#line 248 "Strings.c"
	}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return NULL;
#line 252 "Strings.c"
}


GParamSpec*
app_configs_param_spec_s (const gchar* name,
                          const gchar* nick,
                          const gchar* blurb,
                          GType object_type,
                          GParamFlags flags)
{
	AppConfigsParamSpecS* spec;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_return_val_if_fail (g_type_is_a (object_type, APP_CONFIGS_TYPE_S), NULL);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return G_PARAM_SPEC (spec);
#line 272 "Strings.c"
}


gpointer
app_configs_value_get_s (const GValue* value)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_S), NULL);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return value->data[0].v_pointer;
#line 283 "Strings.c"
}


void
app_configs_value_set_s (GValue* value,
                         gpointer v_object)
{
	AppConfigsS * old;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_S));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	old = value->data[0].v_pointer;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (v_object) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONFIGS_TYPE_S));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = v_object;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		app_configs_s_ref (value->data[0].v_pointer);
#line 306 "Strings.c"
	} else {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = NULL;
#line 310 "Strings.c"
	}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (old) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		app_configs_s_unref (old);
#line 316 "Strings.c"
	}
}


void
app_configs_value_take_s (GValue* value,
                          gpointer v_object)
{
	AppConfigsS * old;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONFIGS_TYPE_S));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	old = value->data[0].v_pointer;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (v_object) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONFIGS_TYPE_S));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = v_object;
#line 338 "Strings.c"
	} else {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		value->data[0].v_pointer = NULL;
#line 342 "Strings.c"
	}
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (old) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		app_configs_s_unref (old);
#line 348 "Strings.c"
	}
}


static void
app_configs_s_class_init (AppConfigsSClass * klass)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	app_configs_s_parent_class = g_type_class_peek_parent (klass);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	((AppConfigsSClass *) klass)->finalize = app_configs_s_finalize;
#line 360 "Strings.c"
}


static void
app_configs_s_instance_init (AppConfigsS * self)
{
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	self->ref_count = 1;
#line 369 "Strings.c"
}


static void
app_configs_s_finalize (AppConfigsS * obj)
{
	AppConfigsS * self;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CONFIGS_TYPE_S, AppConfigsS);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_signal_handlers_destroy (self);
#line 381 "Strings.c"
}


/**
     * The {@code Strings} class is responsible for defining all 
     * the strings for translation used in the application.
     *
     * @since 1.0.0
     */
GType
app_configs_s_get_type (void)
{
	static volatile gsize app_configs_s_type_id__volatile = 0;
	if (g_once_init_enter (&app_configs_s_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { app_configs_value_s_init, app_configs_value_s_free_value, app_configs_value_s_copy_value, app_configs_value_s_peek_pointer, "p", app_configs_value_s_collect_value, "p", app_configs_value_s_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (AppConfigsSClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_configs_s_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppConfigsS), 0, (GInstanceInitFunc) app_configs_s_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType app_configs_s_type_id;
		app_configs_s_type_id = g_type_register_fundamental (g_type_fundamental_next (), "AppConfigsS", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&app_configs_s_type_id__volatile, app_configs_s_type_id);
	}
	return app_configs_s_type_id__volatile;
}


gpointer
app_configs_s_ref (gpointer instance)
{
	AppConfigsS * self;
	self = instance;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	g_atomic_int_inc (&self->ref_count);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	return instance;
#line 416 "Strings.c"
}


void
app_configs_s_unref (gpointer instance)
{
	AppConfigsS * self;
	self = instance;
#line 27 "/run/build/Luna/src/configs/Strings.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		APP_CONFIGS_S_GET_CLASS (self)->finalize (self);
#line 27 "/run/build/Luna/src/configs/Strings.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 431 "Strings.c"
	}
}



