/* Day.c generated by valac 0.40.11, the Vala compiler
 * generated from Day.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define APP_ENUMS_TYPE_DAY (app_enums_day_get_type ())

typedef enum  {
	APP_ENUMS_DAY_MONDAY,
	APP_ENUMS_DAY_TUESDAY,
	APP_ENUMS_DAY_WEDNESDAY,
	APP_ENUMS_DAY_THURSDAY,
	APP_ENUMS_DAY_FRIDAY,
	APP_ENUMS_DAY_SATURDAY,
	APP_ENUMS_DAY_SUNDAY
} AppEnumsDay;



GType app_enums_day_get_type (void) G_GNUC_CONST;
gchar* app_enums_day_to_string (AppEnumsDay self);
#define APP_CONFIGS_S_MONDAY _ ("MON")
#define APP_CONFIGS_S_TUESDAY _ ("TUE")
#define APP_CONFIGS_S_WEDNESDAY _ ("WED")
#define APP_CONFIGS_S_THURSDAY _ ("THU")
#define APP_CONFIGS_S_FRIDAY _ ("FRI")
#define APP_CONFIGS_S_SATURDAT _ ("SAT")
#define APP_CONFIGS_S_SUNDAY _ ("SUN")


gchar*
app_enums_day_to_string (AppEnumsDay self)
{
	gchar* result = NULL;
#line 31 "/run/build/Luna/src/enums/Day.vala"
	switch (self) {
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_MONDAY:
#line 64 "Day.c"
		{
			gchar* _tmp0_;
#line 32 "/run/build/Luna/src/enums/Day.vala"
			_tmp0_ = g_strdup (APP_CONFIGS_S_MONDAY);
#line 32 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp0_;
#line 32 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 73 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_TUESDAY:
#line 77 "Day.c"
		{
			gchar* _tmp1_;
#line 33 "/run/build/Luna/src/enums/Day.vala"
			_tmp1_ = g_strdup (APP_CONFIGS_S_TUESDAY);
#line 33 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp1_;
#line 33 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 86 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_WEDNESDAY:
#line 90 "Day.c"
		{
			gchar* _tmp2_;
#line 34 "/run/build/Luna/src/enums/Day.vala"
			_tmp2_ = g_strdup (APP_CONFIGS_S_WEDNESDAY);
#line 34 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp2_;
#line 34 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 99 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_THURSDAY:
#line 103 "Day.c"
		{
			gchar* _tmp3_;
#line 35 "/run/build/Luna/src/enums/Day.vala"
			_tmp3_ = g_strdup (APP_CONFIGS_S_THURSDAY);
#line 35 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp3_;
#line 35 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 112 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_FRIDAY:
#line 116 "Day.c"
		{
			gchar* _tmp4_;
#line 36 "/run/build/Luna/src/enums/Day.vala"
			_tmp4_ = g_strdup (APP_CONFIGS_S_FRIDAY);
#line 36 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp4_;
#line 36 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 125 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_SATURDAY:
#line 129 "Day.c"
		{
			gchar* _tmp5_;
#line 37 "/run/build/Luna/src/enums/Day.vala"
			_tmp5_ = g_strdup (APP_CONFIGS_S_SATURDAT);
#line 37 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp5_;
#line 37 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 138 "Day.c"
		}
#line 31 "/run/build/Luna/src/enums/Day.vala"
		case APP_ENUMS_DAY_SUNDAY:
#line 142 "Day.c"
		{
			gchar* _tmp6_;
#line 38 "/run/build/Luna/src/enums/Day.vala"
			_tmp6_ = g_strdup (APP_CONFIGS_S_SUNDAY);
#line 38 "/run/build/Luna/src/enums/Day.vala"
			result = _tmp6_;
#line 38 "/run/build/Luna/src/enums/Day.vala"
			return result;
#line 151 "Day.c"
		}
		default:
		{
#line 39 "/run/build/Luna/src/enums/Day.vala"
			g_assert_not_reached ();
#line 157 "Day.c"
		}
	}
}


GType
app_enums_day_get_type (void)
{
	static volatile gsize app_enums_day_type_id__volatile = 0;
	if (g_once_init_enter (&app_enums_day_type_id__volatile)) {
		static const GEnumValue values[] = {{APP_ENUMS_DAY_MONDAY, "APP_ENUMS_DAY_MONDAY", "monday"}, {APP_ENUMS_DAY_TUESDAY, "APP_ENUMS_DAY_TUESDAY", "tuesday"}, {APP_ENUMS_DAY_WEDNESDAY, "APP_ENUMS_DAY_WEDNESDAY", "wednesday"}, {APP_ENUMS_DAY_THURSDAY, "APP_ENUMS_DAY_THURSDAY", "thursday"}, {APP_ENUMS_DAY_FRIDAY, "APP_ENUMS_DAY_FRIDAY", "friday"}, {APP_ENUMS_DAY_SATURDAY, "APP_ENUMS_DAY_SATURDAY", "saturday"}, {APP_ENUMS_DAY_SUNDAY, "APP_ENUMS_DAY_SUNDAY", "sunday"}, {0, NULL, NULL}};
		GType app_enums_day_type_id;
		app_enums_day_type_id = g_enum_register_static ("AppEnumsDay", values);
		g_once_init_leave (&app_enums_day_type_id__volatile, app_enums_day_type_id);
	}
	return app_enums_day_type_id__volatile;
}



