/* AppController.c generated by valac 0.40.11, the Vala compiler
 * generated from AppController.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define APP_CONTROLLERS_TYPE_APP_CONTROLLER (app_controllers_app_controller_get_type ())
#define APP_CONTROLLERS_APP_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CONTROLLERS_TYPE_APP_CONTROLLER, AppControllersAppController))
#define APP_CONTROLLERS_APP_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CONTROLLERS_TYPE_APP_CONTROLLER, AppControllersAppControllerClass))
#define APP_CONTROLLERS_IS_APP_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CONTROLLERS_TYPE_APP_CONTROLLER))
#define APP_CONTROLLERS_IS_APP_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CONTROLLERS_TYPE_APP_CONTROLLER))
#define APP_CONTROLLERS_APP_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CONTROLLERS_TYPE_APP_CONTROLLER, AppControllersAppControllerClass))

typedef struct _AppControllersAppController AppControllersAppController;
typedef struct _AppControllersAppControllerClass AppControllersAppControllerClass;
typedef struct _AppControllersAppControllerPrivate AppControllersAppControllerPrivate;

#define APP_VIEWS_TYPE_APP_VIEW (app_views_app_view_get_type ())
#define APP_VIEWS_APP_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_VIEWS_TYPE_APP_VIEW, AppViewsAppView))
#define APP_VIEWS_APP_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_VIEWS_TYPE_APP_VIEW, AppViewsAppViewClass))
#define APP_VIEWS_IS_APP_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_VIEWS_TYPE_APP_VIEW))
#define APP_VIEWS_IS_APP_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_VIEWS_TYPE_APP_VIEW))
#define APP_VIEWS_APP_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_VIEWS_TYPE_APP_VIEW, AppViewsAppViewClass))

typedef struct _AppViewsAppView AppViewsAppView;
typedef struct _AppViewsAppViewClass AppViewsAppViewClass;

#define APP_TYPE_WINDOW (app_window_get_type ())
#define APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_TYPE_WINDOW, AppWindow))
#define APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_TYPE_WINDOW, AppWindowClass))
#define APP_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_TYPE_WINDOW))
#define APP_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_TYPE_WINDOW))
#define APP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_TYPE_WINDOW, AppWindowClass))

typedef struct _AppWindow AppWindow;
typedef struct _AppWindowClass AppWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define APP_WIDGETS_TYPE_HEADER_BAR (app_widgets_header_bar_get_type ())
#define APP_WIDGETS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_WIDGETS_TYPE_HEADER_BAR, AppWidgetsHeaderBar))
#define APP_WIDGETS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_WIDGETS_TYPE_HEADER_BAR, AppWidgetsHeaderBarClass))
#define APP_WIDGETS_IS_HEADER_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_WIDGETS_TYPE_HEADER_BAR))
#define APP_WIDGETS_IS_HEADER_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_WIDGETS_TYPE_HEADER_BAR))
#define APP_WIDGETS_HEADER_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_WIDGETS_TYPE_HEADER_BAR, AppWidgetsHeaderBarClass))

typedef struct _AppWidgetsHeaderBar AppWidgetsHeaderBar;
typedef struct _AppWidgetsHeaderBarClass AppWidgetsHeaderBarClass;
typedef struct _AppControllersParamSpecAppController AppControllersParamSpecAppController;

struct _AppControllersAppController {
	GTypeInstance parent_instance;
	volatile int ref_count;
	AppControllersAppControllerPrivate * priv;
};

struct _AppControllersAppControllerClass {
	GTypeClass parent_class;
	void (*finalize) (AppControllersAppController *self);
};

struct _AppControllersAppControllerPrivate {
	GtkApplication* application;
	AppViewsAppView* app_view;
	AppWindow* _window;
};

struct _AppControllersParamSpecAppController {
	GParamSpec parent_instance;
};


static gpointer app_controllers_app_controller_parent_class = NULL;

gpointer app_controllers_app_controller_ref (gpointer instance);
void app_controllers_app_controller_unref (gpointer instance);
GParamSpec* app_controllers_param_spec_app_controller (const gchar* name,
                                                       const gchar* nick,
                                                       const gchar* blurb,
                                                       GType object_type,
                                                       GParamFlags flags);
void app_controllers_value_set_app_controller (GValue* value,
                                               gpointer v_object);
void app_controllers_value_take_app_controller (GValue* value,
                                                gpointer v_object);
gpointer app_controllers_value_get_app_controller (const GValue* value);
GType app_controllers_app_controller_get_type (void) G_GNUC_CONST;
GType app_views_app_view_get_type (void) G_GNUC_CONST;
GType app_window_get_type (void) G_GNUC_CONST;
#define APP_CONTROLLERS_APP_CONTROLLER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_CONTROLLERS_TYPE_APP_CONTROLLER, AppControllersAppControllerPrivate))
AppControllersAppController* app_controllers_app_controller_new (GtkApplication* application);
AppControllersAppController* app_controllers_app_controller_construct (GType object_type,
                                                                       GtkApplication* application);
GType app_widgets_header_bar_get_type (void) G_GNUC_CONST;
AppWidgetsHeaderBar* app_widgets_header_bar_new (void);
AppWidgetsHeaderBar* app_widgets_header_bar_construct (GType object_type);
AppWindow* app_window_new (GtkApplication* app);
AppWindow* app_window_construct (GType object_type,
                                 GtkApplication* app);
static void app_controllers_app_controller_set_window (AppControllersAppController* self,
                                                AppWindow* value);
AppViewsAppView* app_views_app_view_new (AppWidgetsHeaderBar* header);
AppViewsAppView* app_views_app_view_construct (GType object_type,
                                               AppWidgetsHeaderBar* header);
static AppWindow* app_controllers_app_controller_get_window (AppControllersAppController* self);
static void __lambda25_ (AppControllersAppController* self);
void app_controllers_app_controller_quit (AppControllersAppController* self);
static void ___lambda25__app_views_app_view_close_clicked (AppViewsAppView* _sender,
                                                    gpointer self);
void app_controllers_app_controller_activate (AppControllersAppController* self);
static void app_controllers_app_controller_finalize (AppControllersAppController * obj);


/**
         * Constructs a new {@code AppController} object.
         */
static gpointer
_g_object_ref0 (gpointer self)
{
#line 41 "/run/build/Luna/src/controllers/AppController.vala"
	return self ? g_object_ref (self) : NULL;
#line 144 "AppController.c"
}


static void
__lambda25_ (AppControllersAppController* self)
{
#line 49 "/run/build/Luna/src/controllers/AppController.vala"
	app_controllers_app_controller_quit (self);
#line 153 "AppController.c"
}


static void
___lambda25__app_views_app_view_close_clicked (AppViewsAppView* _sender,
                                               gpointer self)
{
#line 48 "/run/build/Luna/src/controllers/AppController.vala"
	__lambda25_ ((AppControllersAppController*) self);
#line 163 "AppController.c"
}


AppControllersAppController*
app_controllers_app_controller_construct (GType object_type,
                                          GtkApplication* application)
{
	AppControllersAppController* self = NULL;
	AppWidgetsHeaderBar* header = NULL;
	AppWidgetsHeaderBar* _tmp0_;
	GtkApplication* _tmp1_;
	GtkApplication* _tmp2_;
	AppWindow* _tmp3_;
	AppWindow* _tmp4_;
	AppViewsAppView* _tmp5_;
	AppWindow* _tmp6_;
	AppWindow* _tmp7_;
	AppViewsAppView* _tmp8_;
	GtkApplication* _tmp9_;
	AppWindow* _tmp10_;
	AppViewsAppView* _tmp11_;
#line 38 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 38 "/run/build/Luna/src/controllers/AppController.vala"
	self = (AppControllersAppController*) g_type_create_instance (object_type);
#line 39 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp0_ = app_widgets_header_bar_new ();
#line 39 "/run/build/Luna/src/controllers/AppController.vala"
	g_object_ref_sink (_tmp0_);
#line 39 "/run/build/Luna/src/controllers/AppController.vala"
	header = _tmp0_;
#line 41 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp1_ = _g_object_ref0 (application);
#line 41 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->application);
#line 41 "/run/build/Luna/src/controllers/AppController.vala"
	self->priv->application = _tmp1_;
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp2_ = self->priv->application;
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp3_ = app_window_new (_tmp2_);
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	g_object_ref_sink (_tmp3_);
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp4_ = _tmp3_;
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	app_controllers_app_controller_set_window (self, _tmp4_);
#line 42 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (_tmp4_);
#line 43 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp5_ = app_views_app_view_new (header);
#line 43 "/run/build/Luna/src/controllers/AppController.vala"
	g_object_ref_sink (_tmp5_);
#line 43 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->app_view);
#line 43 "/run/build/Luna/src/controllers/AppController.vala"
	self->priv->app_view = _tmp5_;
#line 44 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp6_ = self->priv->_window;
#line 44 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_window_set_titlebar ((GtkWindow*) _tmp6_, (GtkWidget*) header);
#line 45 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp7_ = self->priv->_window;
#line 45 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp8_ = self->priv->app_view;
#line 45 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_container_add ((GtkContainer*) _tmp7_, (GtkWidget*) _tmp8_);
#line 46 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp9_ = self->priv->application;
#line 46 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp10_ = self->priv->_window;
#line 46 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_application_add_window (_tmp9_, (GtkWindow*) _tmp10_);
#line 48 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp11_ = self->priv->app_view;
#line 48 "/run/build/Luna/src/controllers/AppController.vala"
	g_signal_connect (_tmp11_, "close-clicked", (GCallback) ___lambda25__app_views_app_view_close_clicked, self);
#line 38 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (header);
#line 38 "/run/build/Luna/src/controllers/AppController.vala"
	return self;
#line 245 "AppController.c"
}


AppControllersAppController*
app_controllers_app_controller_new (GtkApplication* application)
{
#line 38 "/run/build/Luna/src/controllers/AppController.vala"
	return app_controllers_app_controller_construct (APP_CONTROLLERS_TYPE_APP_CONTROLLER, application);
#line 254 "AppController.c"
}


void
app_controllers_app_controller_activate (AppControllersAppController* self)
{
	AppWindow* _tmp0_;
	AppViewsAppView* _tmp1_;
#line 53 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_if_fail (self != NULL);
#line 54 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp0_ = self->priv->_window;
#line 54 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
#line 55 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp1_ = self->priv->app_view;
#line 55 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_widget_activate ((GtkWidget*) _tmp1_);
#line 273 "AppController.c"
}


void
app_controllers_app_controller_quit (AppControllersAppController* self)
{
	AppWindow* _tmp0_;
#line 58 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_if_fail (self != NULL);
#line 59 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp0_ = self->priv->_window;
#line 59 "/run/build/Luna/src/controllers/AppController.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
#line 287 "AppController.c"
}


static AppWindow*
app_controllers_app_controller_get_window (AppControllersAppController* self)
{
	AppWindow* result;
	AppWindow* _tmp0_;
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp0_ = self->priv->_window;
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	result = _tmp0_;
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	return result;
#line 304 "AppController.c"
}


static void
app_controllers_app_controller_set_window (AppControllersAppController* self,
                                           AppWindow* value)
{
	AppWindow* _tmp0_;
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_if_fail (self != NULL);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	_tmp0_ = _g_object_ref0 (value);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->_window);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	self->priv->_window = _tmp0_;
#line 321 "AppController.c"
}


static void
app_controllers_value_app_controller_init (GValue* value)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	value->data[0].v_pointer = NULL;
#line 330 "AppController.c"
}


static void
app_controllers_value_app_controller_free_value (GValue* value)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (value->data[0].v_pointer) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		app_controllers_app_controller_unref (value->data[0].v_pointer);
#line 341 "AppController.c"
	}
}


static void
app_controllers_value_app_controller_copy_value (const GValue* src_value,
                                                 GValue* dest_value)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (src_value->data[0].v_pointer) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		dest_value->data[0].v_pointer = app_controllers_app_controller_ref (src_value->data[0].v_pointer);
#line 354 "AppController.c"
	} else {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		dest_value->data[0].v_pointer = NULL;
#line 358 "AppController.c"
	}
}


static gpointer
app_controllers_value_app_controller_peek_pointer (const GValue* value)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return value->data[0].v_pointer;
#line 368 "AppController.c"
}


static gchar*
app_controllers_value_app_controller_collect_value (GValue* value,
                                                    guint n_collect_values,
                                                    GTypeCValue* collect_values,
                                                    guint collect_flags)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (collect_values[0].v_pointer) {
#line 380 "AppController.c"
		AppControllersAppController * object;
		object = collect_values[0].v_pointer;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		if (object->parent_instance.g_class == NULL) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 387 "AppController.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 391 "AppController.c"
		}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = app_controllers_app_controller_ref (object);
#line 395 "AppController.c"
	} else {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = NULL;
#line 399 "AppController.c"
	}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return NULL;
#line 403 "AppController.c"
}


static gchar*
app_controllers_value_app_controller_lcopy_value (const GValue* value,
                                                  guint n_collect_values,
                                                  GTypeCValue* collect_values,
                                                  guint collect_flags)
{
	AppControllersAppController ** object_p;
	object_p = collect_values[0].v_pointer;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (!object_p) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 419 "AppController.c"
	}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (!value->data[0].v_pointer) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		*object_p = NULL;
#line 425 "AppController.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		*object_p = value->data[0].v_pointer;
#line 429 "AppController.c"
	} else {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		*object_p = app_controllers_app_controller_ref (value->data[0].v_pointer);
#line 433 "AppController.c"
	}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return NULL;
#line 437 "AppController.c"
}


GParamSpec*
app_controllers_param_spec_app_controller (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags)
{
	AppControllersParamSpecAppController* spec;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_val_if_fail (g_type_is_a (object_type, APP_CONTROLLERS_TYPE_APP_CONTROLLER), NULL);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return G_PARAM_SPEC (spec);
#line 457 "AppController.c"
}


gpointer
app_controllers_value_get_app_controller (const GValue* value)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONTROLLERS_TYPE_APP_CONTROLLER), NULL);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return value->data[0].v_pointer;
#line 468 "AppController.c"
}


void
app_controllers_value_set_app_controller (GValue* value,
                                          gpointer v_object)
{
	AppControllersAppController * old;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONTROLLERS_TYPE_APP_CONTROLLER));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	old = value->data[0].v_pointer;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (v_object) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONTROLLERS_TYPE_APP_CONTROLLER));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = v_object;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		app_controllers_app_controller_ref (value->data[0].v_pointer);
#line 491 "AppController.c"
	} else {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = NULL;
#line 495 "AppController.c"
	}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (old) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		app_controllers_app_controller_unref (old);
#line 501 "AppController.c"
	}
}


void
app_controllers_value_take_app_controller (GValue* value,
                                           gpointer v_object)
{
	AppControllersAppController * old;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, APP_CONTROLLERS_TYPE_APP_CONTROLLER));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	old = value->data[0].v_pointer;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (v_object) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, APP_CONTROLLERS_TYPE_APP_CONTROLLER));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = v_object;
#line 523 "AppController.c"
	} else {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		value->data[0].v_pointer = NULL;
#line 527 "AppController.c"
	}
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (old) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		app_controllers_app_controller_unref (old);
#line 533 "AppController.c"
	}
}


static void
app_controllers_app_controller_class_init (AppControllersAppControllerClass * klass)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	app_controllers_app_controller_parent_class = g_type_class_peek_parent (klass);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	((AppControllersAppControllerClass *) klass)->finalize = app_controllers_app_controller_finalize;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_type_class_add_private (klass, sizeof (AppControllersAppControllerPrivate));
#line 547 "AppController.c"
}


static void
app_controllers_app_controller_instance_init (AppControllersAppController * self)
{
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	self->priv = APP_CONTROLLERS_APP_CONTROLLER_GET_PRIVATE (self);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	self->priv->_window = NULL;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	self->ref_count = 1;
#line 560 "AppController.c"
}


static void
app_controllers_app_controller_finalize (AppControllersAppController * obj)
{
	AppControllersAppController * self;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_CONTROLLERS_TYPE_APP_CONTROLLER, AppControllersAppController);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_signal_handlers_destroy (self);
#line 31 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->application);
#line 32 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->app_view);
#line 33 "/run/build/Luna/src/controllers/AppController.vala"
	_g_object_unref0 (self->priv->_window);
#line 578 "AppController.c"
}


/**
     * The {@code AppController} class.
     *
     * @since 1.0.0
     */
GType
app_controllers_app_controller_get_type (void)
{
	static volatile gsize app_controllers_app_controller_type_id__volatile = 0;
	if (g_once_init_enter (&app_controllers_app_controller_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { app_controllers_value_app_controller_init, app_controllers_value_app_controller_free_value, app_controllers_value_app_controller_copy_value, app_controllers_value_app_controller_peek_pointer, "p", app_controllers_value_app_controller_collect_value, "p", app_controllers_value_app_controller_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (AppControllersAppControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_controllers_app_controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppControllersAppController), 0, (GInstanceInitFunc) app_controllers_app_controller_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType app_controllers_app_controller_type_id;
		app_controllers_app_controller_type_id = g_type_register_fundamental (g_type_fundamental_next (), "AppControllersAppController", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&app_controllers_app_controller_type_id__volatile, app_controllers_app_controller_type_id);
	}
	return app_controllers_app_controller_type_id__volatile;
}


gpointer
app_controllers_app_controller_ref (gpointer instance)
{
	AppControllersAppController * self;
	self = instance;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	g_atomic_int_inc (&self->ref_count);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	return instance;
#line 612 "AppController.c"
}


void
app_controllers_app_controller_unref (gpointer instance)
{
	AppControllersAppController * self;
	self = instance;
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		APP_CONTROLLERS_APP_CONTROLLER_GET_CLASS (self)->finalize (self);
#line 29 "/run/build/Luna/src/controllers/AppController.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 627 "AppController.c"
	}
}



