/* BottomBar.c generated by valac 0.40.11, the Vala compiler
 * generated from BottomBar.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <granite.h>


#define APP_VIEWS_TYPE_BOTTOM_BAR (app_views_bottom_bar_get_type ())
#define APP_VIEWS_BOTTOM_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBar))
#define APP_VIEWS_BOTTOM_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBarClass))
#define APP_VIEWS_IS_BOTTOM_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_VIEWS_TYPE_BOTTOM_BAR))
#define APP_VIEWS_IS_BOTTOM_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_VIEWS_TYPE_BOTTOM_BAR))
#define APP_VIEWS_BOTTOM_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBarClass))

typedef struct _AppViewsBottomBar AppViewsBottomBar;
typedef struct _AppViewsBottomBarClass AppViewsBottomBarClass;
typedef struct _AppViewsBottomBarPrivate AppViewsBottomBarPrivate;
enum  {
	APP_VIEWS_BOTTOM_BAR_0_PROPERTY,
	APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY,
	APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY,
	APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY,
	APP_VIEWS_BOTTOM_BAR_NUM_PROPERTIES
};
static GParamSpec* app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block4Data Block4Data;

#define APP_VIEWS_TYPE_COLOR_SELECTOR (app_views_color_selector_get_type ())
#define APP_VIEWS_COLOR_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_VIEWS_TYPE_COLOR_SELECTOR, AppViewsColorSelector))
#define APP_VIEWS_COLOR_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_VIEWS_TYPE_COLOR_SELECTOR, AppViewsColorSelectorClass))
#define APP_VIEWS_IS_COLOR_SELECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_VIEWS_TYPE_COLOR_SELECTOR))
#define APP_VIEWS_IS_COLOR_SELECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_VIEWS_TYPE_COLOR_SELECTOR))
#define APP_VIEWS_COLOR_SELECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_VIEWS_TYPE_COLOR_SELECTOR, AppViewsColorSelectorClass))

typedef struct _AppViewsColorSelector AppViewsColorSelector;
typedef struct _AppViewsColorSelectorClass AppViewsColorSelectorClass;

#define APP_CONFIGS_TYPE_SETTINGS (app_configs_settings_get_type ())
#define APP_CONFIGS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettings))
#define APP_CONFIGS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettingsClass))
#define APP_CONFIGS_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_CONFIGS_TYPE_SETTINGS))
#define APP_CONFIGS_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_CONFIGS_TYPE_SETTINGS))
#define APP_CONFIGS_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_CONFIGS_TYPE_SETTINGS, AppConfigsSettingsClass))

typedef struct _AppConfigsSettings AppConfigsSettings;
typedef struct _AppConfigsSettingsClass AppConfigsSettingsClass;

#define APP_ENUMS_TYPE_COLOR (app_enums_color_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	APP_VIEWS_BOTTOM_BAR_TODAY_CLICKED_SIGNAL,
	APP_VIEWS_BOTTOM_BAR_CLOSE_CLICKED_SIGNAL,
	APP_VIEWS_BOTTOM_BAR_NUM_SIGNALS
};
static guint app_views_bottom_bar_signals[APP_VIEWS_BOTTOM_BAR_NUM_SIGNALS] = {0};

struct _AppViewsBottomBar {
	GtkBox parent_instance;
	AppViewsBottomBarPrivate * priv;
};

struct _AppViewsBottomBarClass {
	GtkBoxClass parent_class;
};

struct _AppViewsBottomBarPrivate {
	GtkButton* _menu_button;
	GtkButton* _close_button;
	GtkButton* _today_button;
};

struct _Block4Data {
	int _ref_count_;
	AppViewsBottomBar* self;
	GtkPopover* popup;
};

typedef enum  {
	APP_ENUMS_COLOR_WHITE,
	APP_ENUMS_COLOR_BLACK,
	APP_ENUMS_COLOR_PINK,
	APP_ENUMS_COLOR_RED,
	APP_ENUMS_COLOR_ORANGE,
	APP_ENUMS_COLOR_YELLOW,
	APP_ENUMS_COLOR_GREEN,
	APP_ENUMS_COLOR_TEAL,
	APP_ENUMS_COLOR_BLUE,
	APP_ENUMS_COLOR_PURPLE,
	APP_ENUMS_COLOR_COCO,
	APP_ENUMS_COLOR_GRADIENT_BLUE_GREEN,
	APP_ENUMS_COLOR_GRADIENT_PURPLE_RED,
	APP_ENUMS_COLOR_GRADIENT_PRIDE,
	APP_ENUMS_COLOR_TRANS_WHITE,
	APP_ENUMS_COLOR_TRANS_BLACK,
	APP_ENUMS_COLOR_SEMITRANS_WHITE,
	APP_ENUMS_COLOR_SEMITRANS_BLACK
} AppEnumsColor;


static gpointer app_views_bottom_bar_parent_class = NULL;

GType app_views_bottom_bar_get_type (void) G_GNUC_CONST;
#define APP_VIEWS_BOTTOM_BAR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBarPrivate))
AppViewsBottomBar* app_views_bottom_bar_new (void);
AppViewsBottomBar* app_views_bottom_bar_construct (GType object_type);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
static void app_views_bottom_bar_set_menu_button (AppViewsBottomBar* self,
                                           GtkButton* value);
GtkButton* app_views_bottom_bar_get_menu_button (AppViewsBottomBar* self);
static void app_views_bottom_bar_set_close_button (AppViewsBottomBar* self,
                                            GtkButton* value);
GtkButton* app_views_bottom_bar_get_close_button (AppViewsBottomBar* self);
GType app_views_color_selector_get_type (void) G_GNUC_CONST;
AppViewsColorSelector* app_views_color_selector_new (void);
AppViewsColorSelector* app_views_color_selector_construct (GType object_type);
static void __lambda9_ (Block4Data* _data4_,
                 const gchar* color);
static void app_views_bottom_bar_change_color (AppViewsBottomBar* self,
                                        const gchar* color);
static void app_views_bottom_bar_toggle_popup (AppViewsBottomBar* self,
                                        GtkPopover* popover);
static void ___lambda9__app_views_color_selector_color_selected (AppViewsColorSelector* _sender,
                                                          const gchar* color,
                                                          gpointer self);
static void __lambda10_ (Block4Data* _data4_);
static void ___lambda10__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda11_ (AppViewsBottomBar* self);
static void ___lambda11__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static gboolean __lambda12_ (Block4Data* _data4_);
static gboolean ___lambda12__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                  GdkEventFocus* event,
                                                  gpointer self);
#define APP_CONFIGS_S_GO_TODAY _ ("GO TODAY")
static void app_views_bottom_bar_set_today_button (AppViewsBottomBar* self,
                                            GtkButton* value);
GtkButton* app_views_bottom_bar_get_today_button (AppViewsBottomBar* self);
static void __lambda13_ (AppViewsBottomBar* self);
static void ___lambda13__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
GType app_configs_settings_get_type (void) G_GNUC_CONST;
AppConfigsSettings* app_configs_settings_get_instance (void);
#define APP_CONFIGS_CONSTANTS_URL_CSS_WHITE "/com/github/calo001/luna/css/style_white.css"
GType app_enums_color_get_type (void) G_GNUC_CONST;
gchar* app_enums_color_to_string (AppEnumsColor self);
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK "/com/github/calo001/luna/css/style_dark.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PINK "/com/github/calo001/luna/css/style_pink.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_RED "/com/github/calo001/luna/css/style_red.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_ORANGE "/com/github/calo001/luna/css/style_orange.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_YELLOW "/com/github/calo001/luna/css/style_yellow.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GREEN "/com/github/calo001/luna/css/style_green.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_TEAL "/com/github/calo001/luna/css/style_teal.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_BLUE "/com/github/calo001/luna/css/style_blue.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PURPLE "/com/github/calo001/luna/css/style_purple.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_COCO "/com/github/calo001/luna/css/style_coco.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_BLUE_GREEN "/com/github/calo001/luna/css/style_gradient_blue_green.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_PURPLE_RED "/com/github/calo001/luna/css/style_gradient_purple_red.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_PRIDE "/com/github/calo001/luna/css/style_gradient_pride.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_TRANS "/com/github/calo001/luna/css/style_light_transparent.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK_TRANS "/com/github/calo001/luna/css/style_dark_transparent.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_SEMITRANS "/com/github/calo001/luna/css/style_light_semitrans.css"
#define APP_CONFIGS_CONSTANTS_URL_CSS_DARK_SEMITRANS "/com/github/calo001/luna/css/style_dark_semitrans.css"
void app_configs_settings_set_color (AppConfigsSettings* self,
                                     const gchar* value);
static void app_views_bottom_bar_finalize (GObject * obj);
static void _vala_app_views_bottom_bar_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec);
static void _vala_app_views_bottom_bar_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec);


static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	g_atomic_int_inc (&_data4_->_ref_count_);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	return _data4_;
#line 212 "BottomBar.c"
}


static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
#line 223 "BottomBar.c"
		AppViewsBottomBar* self;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
		self = _data4_->self;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
		_g_object_unref0 (_data4_->popup);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
		_g_object_unref0 (self);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
		g_slice_free (Block4Data, _data4_);
#line 233 "BottomBar.c"
	}
}


static void
__lambda9_ (Block4Data* _data4_,
            const gchar* color)
{
	AppViewsBottomBar* self;
#line 57 "/run/build/Luna/src/views/BottomBar.vala"
	self = _data4_->self;
#line 57 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (color != NULL);
#line 58 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_change_color (self, color);
#line 59 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_toggle_popup (self, _data4_->popup);
#line 251 "BottomBar.c"
}


static void
___lambda9__app_views_color_selector_color_selected (AppViewsColorSelector* _sender,
                                                     const gchar* color,
                                                     gpointer self)
{
#line 57 "/run/build/Luna/src/views/BottomBar.vala"
	__lambda9_ (self, color);
#line 262 "BottomBar.c"
}


static void
__lambda10_ (Block4Data* _data4_)
{
	AppViewsBottomBar* self;
#line 62 "/run/build/Luna/src/views/BottomBar.vala"
	self = _data4_->self;
#line 63 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_toggle_popup (self, _data4_->popup);
#line 274 "BottomBar.c"
}


static void
___lambda10__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 62 "/run/build/Luna/src/views/BottomBar.vala"
	__lambda10_ (self);
#line 284 "BottomBar.c"
}


static void
__lambda11_ (AppViewsBottomBar* self)
{
#line 67 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_emit (self, app_views_bottom_bar_signals[APP_VIEWS_BOTTOM_BAR_CLOSE_CLICKED_SIGNAL], 0);
#line 293 "BottomBar.c"
}


static void
___lambda11__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 66 "/run/build/Luna/src/views/BottomBar.vala"
	__lambda11_ ((AppViewsBottomBar*) self);
#line 303 "BottomBar.c"
}


static gboolean
__lambda12_ (Block4Data* _data4_)
{
	AppViewsBottomBar* self;
	gboolean result = FALSE;
#line 70 "/run/build/Luna/src/views/BottomBar.vala"
	self = _data4_->self;
#line 71 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_widget_set_visible ((GtkWidget*) _data4_->popup, FALSE);
#line 72 "/run/build/Luna/src/views/BottomBar.vala"
	result = TRUE;
#line 72 "/run/build/Luna/src/views/BottomBar.vala"
	return result;
#line 320 "BottomBar.c"
}


static gboolean
___lambda12__gtk_widget_focus_out_event (GtkWidget* _sender,
                                         GdkEventFocus* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda12_ (self);
#line 70 "/run/build/Luna/src/views/BottomBar.vala"
	return result;
#line 333 "BottomBar.c"
}


static void
__lambda13_ (AppViewsBottomBar* self)
{
#line 79 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_emit (self, app_views_bottom_bar_signals[APP_VIEWS_BOTTOM_BAR_TODAY_CLICKED_SIGNAL], 0);
#line 342 "BottomBar.c"
}


static void
___lambda13__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 78 "/run/build/Luna/src/views/BottomBar.vala"
	__lambda13_ ((AppViewsBottomBar*) self);
#line 352 "BottomBar.c"
}


AppViewsBottomBar*
app_views_bottom_bar_construct (GType object_type)
{
	AppViewsBottomBar * self = NULL;
	Block4Data* _data4_;
	GtkStyleContext* _tmp0_;
	GtkButton* _tmp1_;
	GtkButton* _tmp2_;
	GtkButton* _tmp3_;
	GtkButton* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkButton* _tmp6_;
	GtkButton* _tmp7_;
	GtkButton* _tmp8_;
	GtkButton* _tmp9_;
	GtkButton* _tmp10_;
	GtkStyleContext* _tmp11_;
	GtkButton* _tmp12_;
	GtkButton* _tmp13_;
	GtkPopover* _tmp14_;
	AppViewsColorSelector* colors = NULL;
	AppViewsColorSelector* _tmp15_;
	GtkButton* _tmp16_;
	GtkButton* _tmp17_;
	GtkButton* _tmp18_;
	GtkButton* _tmp19_;
	GtkButton* _tmp20_;
	GtkButton* _tmp21_;
	GtkButton* _tmp22_;
	GtkStyleContext* _tmp23_;
	GtkButton* _tmp24_;
	GtkButton* _tmp25_;
	GtkButton* _tmp26_;
	GtkButton* _tmp27_;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	_data4_ = g_slice_new0 (Block4Data);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	_data4_->_ref_count_ = 1;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	self = (AppViewsBottomBar*) g_object_new (object_type, NULL);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	_data4_->self = g_object_ref (self);
#line 37 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp0_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 37 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_style_context_add_class (_tmp0_, "buttombar");
#line 39 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp1_ = (GtkButton*) gtk_button_new_from_icon_name ("view-more-horizontal-symbolic", (GtkIconSize) GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 39 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_ref_sink (_tmp1_);
#line 39 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp2_ = _tmp1_;
#line 39 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_set_menu_button (self, _tmp2_);
#line 39 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (_tmp2_);
#line 40 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp3_ = self->priv->_menu_button;
#line 40 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp3_, _ ("Colors"));
#line 41 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp4_ = self->priv->_menu_button;
#line 41 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp5_ = gtk_widget_get_style_context ((GtkWidget*) _tmp4_);
#line 41 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_style_context_add_class (_tmp5_, "flat");
#line 42 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp6_ = self->priv->_menu_button;
#line 42 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_set ((GtkWidget*) _tmp6_, "margin", 8, NULL);
#line 44 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp7_ = (GtkButton*) gtk_button_new_from_icon_name ("window-close-symbolic", (GtkIconSize) GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 44 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_ref_sink (_tmp7_);
#line 44 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp8_ = _tmp7_;
#line 44 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_set_close_button (self, _tmp8_);
#line 44 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (_tmp8_);
#line 45 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp9_ = self->priv->_close_button;
#line 45 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp9_, _ ("Close"));
#line 46 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp10_ = self->priv->_close_button;
#line 46 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
#line 46 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_style_context_add_class (_tmp11_, "flat");
#line 47 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp12_ = self->priv->_close_button;
#line 47 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_set ((GtkWidget*) _tmp12_, "margin", 8, NULL);
#line 49 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp13_ = self->priv->_menu_button;
#line 49 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp14_ = (GtkPopover*) gtk_popover_new ((GtkWidget*) _tmp13_);
#line 49 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_ref_sink (_tmp14_);
#line 49 "/run/build/Luna/src/views/BottomBar.vala"
	_data4_->popup = _tmp14_;
#line 50 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_popover_set_position (_data4_->popup, GTK_POS_BOTTOM);
#line 51 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_popover_set_modal (_data4_->popup, FALSE);
#line 53 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp15_ = app_views_color_selector_new ();
#line 53 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_ref_sink (_tmp15_);
#line 53 "/run/build/Luna/src/views/BottomBar.vala"
	colors = _tmp15_;
#line 54 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_widget_show_all ((GtkWidget*) colors);
#line 55 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_container_add ((GtkContainer*) _data4_->popup, (GtkWidget*) colors);
#line 57 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_connect_data (colors, "color-selected", (GCallback) ___lambda9__app_views_color_selector_color_selected, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 62 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp16_ = self->priv->_menu_button;
#line 62 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_connect_data (_tmp16_, "clicked", (GCallback) ___lambda10__gtk_button_clicked, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 66 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp17_ = self->priv->_close_button;
#line 66 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_connect_object (_tmp17_, "clicked", (GCallback) ___lambda11__gtk_button_clicked, self, 0);
#line 70 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp18_ = self->priv->_menu_button;
#line 70 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_connect_data ((GtkWidget*) _tmp18_, "focus-out-event", (GCallback) ___lambda12__gtk_widget_focus_out_event, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 75 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp19_ = (GtkButton*) gtk_button_new_with_label (APP_CONFIGS_S_GO_TODAY);
#line 75 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_ref_sink (_tmp19_);
#line 75 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp20_ = _tmp19_;
#line 75 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_set_today_button (self, _tmp20_);
#line 75 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (_tmp20_);
#line 76 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp21_ = self->priv->_today_button;
#line 76 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_set ((GtkWidget*) _tmp21_, "margin", 8, NULL);
#line 77 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp22_ = self->priv->_today_button;
#line 77 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp23_ = gtk_widget_get_style_context ((GtkWidget*) _tmp22_);
#line 77 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_style_context_add_class (_tmp23_, "gotoday");
#line 78 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp24_ = self->priv->_today_button;
#line 78 "/run/build/Luna/src/views/BottomBar.vala"
	g_signal_connect_object (_tmp24_, "clicked", (GCallback) ___lambda13__gtk_button_clicked, self, 0);
#line 82 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp25_ = self->priv->_close_button;
#line 82 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp25_, TRUE, TRUE, (guint) 0);
#line 83 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp26_ = self->priv->_today_button;
#line 83 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp26_, TRUE, TRUE, (guint) 0);
#line 84 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp27_ = self->priv->_menu_button;
#line 84 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) _tmp27_, TRUE, TRUE, (guint) 0);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (colors);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	block4_data_unref (_data4_);
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	_data4_ = NULL;
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	return self;
#line 530 "BottomBar.c"
}


AppViewsBottomBar*
app_views_bottom_bar_new (void)
{
#line 36 "/run/build/Luna/src/views/BottomBar.vala"
	return app_views_bottom_bar_construct (APP_VIEWS_TYPE_BOTTOM_BAR);
#line 539 "BottomBar.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 88 "/run/build/Luna/src/views/BottomBar.vala"
	return self ? g_object_ref (self) : NULL;
#line 548 "BottomBar.c"
}


static void
app_views_bottom_bar_change_color (AppViewsBottomBar* self,
                                   const gchar* color)
{
	AppConfigsSettings* settings = NULL;
	AppConfigsSettings* _tmp0_;
	AppConfigsSettings* _tmp1_;
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp2_;
	gchar* url_css = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gboolean _tmp6_;
	AppConfigsSettings* _tmp80_;
	GtkCssProvider* _tmp81_;
	const gchar* _tmp82_;
	GdkScreen* _tmp83_;
	GtkCssProvider* _tmp84_;
#line 87 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (self != NULL);
#line 87 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (color != NULL);
#line 88 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp0_ = app_configs_settings_get_instance ();
#line 88 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 88 "/run/build/Luna/src/views/BottomBar.vala"
	settings = _tmp1_;
#line 89 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp2_ = gtk_css_provider_new ();
#line 89 "/run/build/Luna/src/views/BottomBar.vala"
	css_provider = _tmp2_;
#line 90 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp3_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_WHITE);
#line 90 "/run/build/Luna/src/views/BottomBar.vala"
	url_css = _tmp3_;
#line 92 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp4_ = app_enums_color_to_string (APP_ENUMS_COLOR_WHITE);
#line 92 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp5_ = _tmp4_;
#line 92 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp6_ = g_strcmp0 (color, _tmp5_) == 0;
#line 92 "/run/build/Luna/src/views/BottomBar.vala"
	_g_free0 (_tmp5_);
#line 92 "/run/build/Luna/src/views/BottomBar.vala"
	if (_tmp6_) {
#line 599 "BottomBar.c"
		gchar* _tmp7_;
#line 93 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp7_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_WHITE);
#line 93 "/run/build/Luna/src/views/BottomBar.vala"
		_g_free0 (url_css);
#line 93 "/run/build/Luna/src/views/BottomBar.vala"
		url_css = _tmp7_;
#line 607 "BottomBar.c"
	} else {
		gchar* _tmp8_;
		gchar* _tmp9_;
		gboolean _tmp10_;
#line 94 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp8_ = app_enums_color_to_string (APP_ENUMS_COLOR_BLACK);
#line 94 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp9_ = _tmp8_;
#line 94 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp10_ = g_strcmp0 (color, _tmp9_) == 0;
#line 94 "/run/build/Luna/src/views/BottomBar.vala"
		_g_free0 (_tmp9_);
#line 94 "/run/build/Luna/src/views/BottomBar.vala"
		if (_tmp10_) {
#line 622 "BottomBar.c"
			gchar* _tmp11_;
#line 95 "/run/build/Luna/src/views/BottomBar.vala"
			_tmp11_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_DARK);
#line 95 "/run/build/Luna/src/views/BottomBar.vala"
			_g_free0 (url_css);
#line 95 "/run/build/Luna/src/views/BottomBar.vala"
			url_css = _tmp11_;
#line 630 "BottomBar.c"
		} else {
			gchar* _tmp12_;
			gchar* _tmp13_;
			gboolean _tmp14_;
#line 96 "/run/build/Luna/src/views/BottomBar.vala"
			_tmp12_ = app_enums_color_to_string (APP_ENUMS_COLOR_PINK);
#line 96 "/run/build/Luna/src/views/BottomBar.vala"
			_tmp13_ = _tmp12_;
#line 96 "/run/build/Luna/src/views/BottomBar.vala"
			_tmp14_ = g_strcmp0 (color, _tmp13_) == 0;
#line 96 "/run/build/Luna/src/views/BottomBar.vala"
			_g_free0 (_tmp13_);
#line 96 "/run/build/Luna/src/views/BottomBar.vala"
			if (_tmp14_) {
#line 645 "BottomBar.c"
				gchar* _tmp15_;
#line 97 "/run/build/Luna/src/views/BottomBar.vala"
				_tmp15_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_PINK);
#line 97 "/run/build/Luna/src/views/BottomBar.vala"
				_g_free0 (url_css);
#line 97 "/run/build/Luna/src/views/BottomBar.vala"
				url_css = _tmp15_;
#line 653 "BottomBar.c"
			} else {
				gchar* _tmp16_;
				gchar* _tmp17_;
				gboolean _tmp18_;
#line 98 "/run/build/Luna/src/views/BottomBar.vala"
				_tmp16_ = app_enums_color_to_string (APP_ENUMS_COLOR_RED);
#line 98 "/run/build/Luna/src/views/BottomBar.vala"
				_tmp17_ = _tmp16_;
#line 98 "/run/build/Luna/src/views/BottomBar.vala"
				_tmp18_ = g_strcmp0 (color, _tmp17_) == 0;
#line 98 "/run/build/Luna/src/views/BottomBar.vala"
				_g_free0 (_tmp17_);
#line 98 "/run/build/Luna/src/views/BottomBar.vala"
				if (_tmp18_) {
#line 668 "BottomBar.c"
					gchar* _tmp19_;
#line 99 "/run/build/Luna/src/views/BottomBar.vala"
					_tmp19_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_RED);
#line 99 "/run/build/Luna/src/views/BottomBar.vala"
					_g_free0 (url_css);
#line 99 "/run/build/Luna/src/views/BottomBar.vala"
					url_css = _tmp19_;
#line 676 "BottomBar.c"
				} else {
					gchar* _tmp20_;
					gchar* _tmp21_;
					gboolean _tmp22_;
#line 100 "/run/build/Luna/src/views/BottomBar.vala"
					_tmp20_ = app_enums_color_to_string (APP_ENUMS_COLOR_ORANGE);
#line 100 "/run/build/Luna/src/views/BottomBar.vala"
					_tmp21_ = _tmp20_;
#line 100 "/run/build/Luna/src/views/BottomBar.vala"
					_tmp22_ = g_strcmp0 (color, _tmp21_) == 0;
#line 100 "/run/build/Luna/src/views/BottomBar.vala"
					_g_free0 (_tmp21_);
#line 100 "/run/build/Luna/src/views/BottomBar.vala"
					if (_tmp22_) {
#line 691 "BottomBar.c"
						gchar* _tmp23_;
#line 101 "/run/build/Luna/src/views/BottomBar.vala"
						_tmp23_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_ORANGE);
#line 101 "/run/build/Luna/src/views/BottomBar.vala"
						_g_free0 (url_css);
#line 101 "/run/build/Luna/src/views/BottomBar.vala"
						url_css = _tmp23_;
#line 699 "BottomBar.c"
					} else {
						gchar* _tmp24_;
						gchar* _tmp25_;
						gboolean _tmp26_;
#line 102 "/run/build/Luna/src/views/BottomBar.vala"
						_tmp24_ = app_enums_color_to_string (APP_ENUMS_COLOR_YELLOW);
#line 102 "/run/build/Luna/src/views/BottomBar.vala"
						_tmp25_ = _tmp24_;
#line 102 "/run/build/Luna/src/views/BottomBar.vala"
						_tmp26_ = g_strcmp0 (color, _tmp25_) == 0;
#line 102 "/run/build/Luna/src/views/BottomBar.vala"
						_g_free0 (_tmp25_);
#line 102 "/run/build/Luna/src/views/BottomBar.vala"
						if (_tmp26_) {
#line 714 "BottomBar.c"
							gchar* _tmp27_;
#line 103 "/run/build/Luna/src/views/BottomBar.vala"
							_tmp27_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_YELLOW);
#line 103 "/run/build/Luna/src/views/BottomBar.vala"
							_g_free0 (url_css);
#line 103 "/run/build/Luna/src/views/BottomBar.vala"
							url_css = _tmp27_;
#line 722 "BottomBar.c"
						} else {
							gchar* _tmp28_;
							gchar* _tmp29_;
							gboolean _tmp30_;
#line 104 "/run/build/Luna/src/views/BottomBar.vala"
							_tmp28_ = app_enums_color_to_string (APP_ENUMS_COLOR_GREEN);
#line 104 "/run/build/Luna/src/views/BottomBar.vala"
							_tmp29_ = _tmp28_;
#line 104 "/run/build/Luna/src/views/BottomBar.vala"
							_tmp30_ = g_strcmp0 (color, _tmp29_) == 0;
#line 104 "/run/build/Luna/src/views/BottomBar.vala"
							_g_free0 (_tmp29_);
#line 104 "/run/build/Luna/src/views/BottomBar.vala"
							if (_tmp30_) {
#line 737 "BottomBar.c"
								gchar* _tmp31_;
#line 105 "/run/build/Luna/src/views/BottomBar.vala"
								_tmp31_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_GREEN);
#line 105 "/run/build/Luna/src/views/BottomBar.vala"
								_g_free0 (url_css);
#line 105 "/run/build/Luna/src/views/BottomBar.vala"
								url_css = _tmp31_;
#line 745 "BottomBar.c"
							} else {
								gchar* _tmp32_;
								gchar* _tmp33_;
								gboolean _tmp34_;
#line 106 "/run/build/Luna/src/views/BottomBar.vala"
								_tmp32_ = app_enums_color_to_string (APP_ENUMS_COLOR_TEAL);
#line 106 "/run/build/Luna/src/views/BottomBar.vala"
								_tmp33_ = _tmp32_;
#line 106 "/run/build/Luna/src/views/BottomBar.vala"
								_tmp34_ = g_strcmp0 (color, _tmp33_) == 0;
#line 106 "/run/build/Luna/src/views/BottomBar.vala"
								_g_free0 (_tmp33_);
#line 106 "/run/build/Luna/src/views/BottomBar.vala"
								if (_tmp34_) {
#line 760 "BottomBar.c"
									gchar* _tmp35_;
#line 107 "/run/build/Luna/src/views/BottomBar.vala"
									_tmp35_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_TEAL);
#line 107 "/run/build/Luna/src/views/BottomBar.vala"
									_g_free0 (url_css);
#line 107 "/run/build/Luna/src/views/BottomBar.vala"
									url_css = _tmp35_;
#line 768 "BottomBar.c"
								} else {
									gchar* _tmp36_;
									gchar* _tmp37_;
									gboolean _tmp38_;
#line 108 "/run/build/Luna/src/views/BottomBar.vala"
									_tmp36_ = app_enums_color_to_string (APP_ENUMS_COLOR_BLUE);
#line 108 "/run/build/Luna/src/views/BottomBar.vala"
									_tmp37_ = _tmp36_;
#line 108 "/run/build/Luna/src/views/BottomBar.vala"
									_tmp38_ = g_strcmp0 (color, _tmp37_) == 0;
#line 108 "/run/build/Luna/src/views/BottomBar.vala"
									_g_free0 (_tmp37_);
#line 108 "/run/build/Luna/src/views/BottomBar.vala"
									if (_tmp38_) {
#line 783 "BottomBar.c"
										gchar* _tmp39_;
#line 109 "/run/build/Luna/src/views/BottomBar.vala"
										_tmp39_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_BLUE);
#line 109 "/run/build/Luna/src/views/BottomBar.vala"
										_g_free0 (url_css);
#line 109 "/run/build/Luna/src/views/BottomBar.vala"
										url_css = _tmp39_;
#line 791 "BottomBar.c"
									} else {
										gchar* _tmp40_;
										gchar* _tmp41_;
										gboolean _tmp42_;
#line 110 "/run/build/Luna/src/views/BottomBar.vala"
										_tmp40_ = app_enums_color_to_string (APP_ENUMS_COLOR_PURPLE);
#line 110 "/run/build/Luna/src/views/BottomBar.vala"
										_tmp41_ = _tmp40_;
#line 110 "/run/build/Luna/src/views/BottomBar.vala"
										_tmp42_ = g_strcmp0 (color, _tmp41_) == 0;
#line 110 "/run/build/Luna/src/views/BottomBar.vala"
										_g_free0 (_tmp41_);
#line 110 "/run/build/Luna/src/views/BottomBar.vala"
										if (_tmp42_) {
#line 806 "BottomBar.c"
											gchar* _tmp43_;
#line 111 "/run/build/Luna/src/views/BottomBar.vala"
											_tmp43_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_PURPLE);
#line 111 "/run/build/Luna/src/views/BottomBar.vala"
											_g_free0 (url_css);
#line 111 "/run/build/Luna/src/views/BottomBar.vala"
											url_css = _tmp43_;
#line 814 "BottomBar.c"
										} else {
											gchar* _tmp44_;
											gchar* _tmp45_;
											gboolean _tmp46_;
#line 112 "/run/build/Luna/src/views/BottomBar.vala"
											_tmp44_ = app_enums_color_to_string (APP_ENUMS_COLOR_COCO);
#line 112 "/run/build/Luna/src/views/BottomBar.vala"
											_tmp45_ = _tmp44_;
#line 112 "/run/build/Luna/src/views/BottomBar.vala"
											_tmp46_ = g_strcmp0 (color, _tmp45_) == 0;
#line 112 "/run/build/Luna/src/views/BottomBar.vala"
											_g_free0 (_tmp45_);
#line 112 "/run/build/Luna/src/views/BottomBar.vala"
											if (_tmp46_) {
#line 829 "BottomBar.c"
												gchar* _tmp47_;
#line 113 "/run/build/Luna/src/views/BottomBar.vala"
												_tmp47_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_COCO);
#line 113 "/run/build/Luna/src/views/BottomBar.vala"
												_g_free0 (url_css);
#line 113 "/run/build/Luna/src/views/BottomBar.vala"
												url_css = _tmp47_;
#line 837 "BottomBar.c"
											} else {
												gchar* _tmp48_;
												gchar* _tmp49_;
												gboolean _tmp50_;
#line 114 "/run/build/Luna/src/views/BottomBar.vala"
												_tmp48_ = app_enums_color_to_string (APP_ENUMS_COLOR_GRADIENT_BLUE_GREEN);
#line 114 "/run/build/Luna/src/views/BottomBar.vala"
												_tmp49_ = _tmp48_;
#line 114 "/run/build/Luna/src/views/BottomBar.vala"
												_tmp50_ = g_strcmp0 (color, _tmp49_) == 0;
#line 114 "/run/build/Luna/src/views/BottomBar.vala"
												_g_free0 (_tmp49_);
#line 114 "/run/build/Luna/src/views/BottomBar.vala"
												if (_tmp50_) {
#line 852 "BottomBar.c"
													gchar* _tmp51_;
#line 115 "/run/build/Luna/src/views/BottomBar.vala"
													_tmp51_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_BLUE_GREEN);
#line 115 "/run/build/Luna/src/views/BottomBar.vala"
													_g_free0 (url_css);
#line 115 "/run/build/Luna/src/views/BottomBar.vala"
													url_css = _tmp51_;
#line 860 "BottomBar.c"
												} else {
													gchar* _tmp52_;
													gchar* _tmp53_;
													gboolean _tmp54_;
#line 116 "/run/build/Luna/src/views/BottomBar.vala"
													_tmp52_ = app_enums_color_to_string (APP_ENUMS_COLOR_GRADIENT_PURPLE_RED);
#line 116 "/run/build/Luna/src/views/BottomBar.vala"
													_tmp53_ = _tmp52_;
#line 116 "/run/build/Luna/src/views/BottomBar.vala"
													_tmp54_ = g_strcmp0 (color, _tmp53_) == 0;
#line 116 "/run/build/Luna/src/views/BottomBar.vala"
													_g_free0 (_tmp53_);
#line 116 "/run/build/Luna/src/views/BottomBar.vala"
													if (_tmp54_) {
#line 875 "BottomBar.c"
														gchar* _tmp55_;
#line 117 "/run/build/Luna/src/views/BottomBar.vala"
														_tmp55_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_GRADIENT_PURPLE_RED);
#line 117 "/run/build/Luna/src/views/BottomBar.vala"
														_g_free0 (url_css);
#line 117 "/run/build/Luna/src/views/BottomBar.vala"
														url_css = _tmp55_;
#line 883 "BottomBar.c"
													} else {
														gchar* _tmp56_;
														gchar* _tmp57_;
														gboolean _tmp58_;
#line 118 "/run/build/Luna/src/views/BottomBar.vala"
														_tmp56_ = app_enums_color_to_string (APP_ENUMS_COLOR_GRADIENT_PRIDE);
#line 118 "/run/build/Luna/src/views/BottomBar.vala"
														_tmp57_ = _tmp56_;
#line 118 "/run/build/Luna/src/views/BottomBar.vala"
														_tmp58_ = g_strcmp0 (color, _tmp57_) == 0;
#line 118 "/run/build/Luna/src/views/BottomBar.vala"
														_g_free0 (_tmp57_);
#line 118 "/run/build/Luna/src/views/BottomBar.vala"
														if (_tmp58_) {
#line 898 "BottomBar.c"
															gchar* _tmp59_;
#line 119 "/run/build/Luna/src/views/BottomBar.vala"
															_tmp59_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_PRIDE);
#line 119 "/run/build/Luna/src/views/BottomBar.vala"
															_g_free0 (url_css);
#line 119 "/run/build/Luna/src/views/BottomBar.vala"
															url_css = _tmp59_;
#line 906 "BottomBar.c"
														} else {
															gchar* _tmp60_;
															gchar* _tmp61_;
															gboolean _tmp62_;
#line 120 "/run/build/Luna/src/views/BottomBar.vala"
															_tmp60_ = app_enums_color_to_string (APP_ENUMS_COLOR_TRANS_WHITE);
#line 120 "/run/build/Luna/src/views/BottomBar.vala"
															_tmp61_ = _tmp60_;
#line 120 "/run/build/Luna/src/views/BottomBar.vala"
															_tmp62_ = g_strcmp0 (color, _tmp61_) == 0;
#line 120 "/run/build/Luna/src/views/BottomBar.vala"
															_g_free0 (_tmp61_);
#line 120 "/run/build/Luna/src/views/BottomBar.vala"
															if (_tmp62_) {
#line 921 "BottomBar.c"
																gchar* _tmp63_;
#line 121 "/run/build/Luna/src/views/BottomBar.vala"
																_tmp63_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_TRANS);
#line 121 "/run/build/Luna/src/views/BottomBar.vala"
																_g_free0 (url_css);
#line 121 "/run/build/Luna/src/views/BottomBar.vala"
																url_css = _tmp63_;
#line 929 "BottomBar.c"
															} else {
																gchar* _tmp64_;
																gchar* _tmp65_;
																gboolean _tmp66_;
#line 122 "/run/build/Luna/src/views/BottomBar.vala"
																_tmp64_ = app_enums_color_to_string (APP_ENUMS_COLOR_TRANS_BLACK);
#line 122 "/run/build/Luna/src/views/BottomBar.vala"
																_tmp65_ = _tmp64_;
#line 122 "/run/build/Luna/src/views/BottomBar.vala"
																_tmp66_ = g_strcmp0 (color, _tmp65_) == 0;
#line 122 "/run/build/Luna/src/views/BottomBar.vala"
																_g_free0 (_tmp65_);
#line 122 "/run/build/Luna/src/views/BottomBar.vala"
																if (_tmp66_) {
#line 944 "BottomBar.c"
																	gchar* _tmp67_;
#line 123 "/run/build/Luna/src/views/BottomBar.vala"
																	_tmp67_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_DARK_TRANS);
#line 123 "/run/build/Luna/src/views/BottomBar.vala"
																	_g_free0 (url_css);
#line 123 "/run/build/Luna/src/views/BottomBar.vala"
																	url_css = _tmp67_;
#line 952 "BottomBar.c"
																} else {
																	gchar* _tmp68_;
																	gchar* _tmp69_;
																	gboolean _tmp70_;
#line 124 "/run/build/Luna/src/views/BottomBar.vala"
																	_tmp68_ = app_enums_color_to_string (APP_ENUMS_COLOR_SEMITRANS_WHITE);
#line 124 "/run/build/Luna/src/views/BottomBar.vala"
																	_tmp69_ = _tmp68_;
#line 124 "/run/build/Luna/src/views/BottomBar.vala"
																	_tmp70_ = g_strcmp0 (color, _tmp69_) == 0;
#line 124 "/run/build/Luna/src/views/BottomBar.vala"
																	_g_free0 (_tmp69_);
#line 124 "/run/build/Luna/src/views/BottomBar.vala"
																	if (_tmp70_) {
#line 967 "BottomBar.c"
																		gchar* _tmp71_;
#line 125 "/run/build/Luna/src/views/BottomBar.vala"
																		_tmp71_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_LIGHT_SEMITRANS);
#line 125 "/run/build/Luna/src/views/BottomBar.vala"
																		_g_free0 (url_css);
#line 125 "/run/build/Luna/src/views/BottomBar.vala"
																		url_css = _tmp71_;
#line 975 "BottomBar.c"
																	} else {
																		gchar* _tmp72_;
																		gchar* _tmp73_;
																		gboolean _tmp74_;
#line 126 "/run/build/Luna/src/views/BottomBar.vala"
																		_tmp72_ = app_enums_color_to_string (APP_ENUMS_COLOR_SEMITRANS_BLACK);
#line 126 "/run/build/Luna/src/views/BottomBar.vala"
																		_tmp73_ = _tmp72_;
#line 126 "/run/build/Luna/src/views/BottomBar.vala"
																		_tmp74_ = g_strcmp0 (color, _tmp73_) == 0;
#line 126 "/run/build/Luna/src/views/BottomBar.vala"
																		_g_free0 (_tmp73_);
#line 126 "/run/build/Luna/src/views/BottomBar.vala"
																		if (_tmp74_) {
#line 990 "BottomBar.c"
																			gchar* _tmp75_;
#line 127 "/run/build/Luna/src/views/BottomBar.vala"
																			_tmp75_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_DARK_SEMITRANS);
#line 127 "/run/build/Luna/src/views/BottomBar.vala"
																			_g_free0 (url_css);
#line 127 "/run/build/Luna/src/views/BottomBar.vala"
																			url_css = _tmp75_;
#line 998 "BottomBar.c"
																		} else {
																			AppConfigsSettings* _tmp76_;
																			gchar* _tmp77_;
																			gchar* _tmp78_;
																			gchar* _tmp79_;
#line 129 "/run/build/Luna/src/views/BottomBar.vala"
																			_tmp76_ = settings;
#line 129 "/run/build/Luna/src/views/BottomBar.vala"
																			_tmp77_ = app_enums_color_to_string (APP_ENUMS_COLOR_WHITE);
#line 129 "/run/build/Luna/src/views/BottomBar.vala"
																			_tmp78_ = _tmp77_;
#line 129 "/run/build/Luna/src/views/BottomBar.vala"
																			app_configs_settings_set_color (_tmp76_, _tmp78_);
#line 129 "/run/build/Luna/src/views/BottomBar.vala"
																			_g_free0 (_tmp78_);
#line 130 "/run/build/Luna/src/views/BottomBar.vala"
																			_tmp79_ = g_strdup (APP_CONFIGS_CONSTANTS_URL_CSS_WHITE);
#line 130 "/run/build/Luna/src/views/BottomBar.vala"
																			_g_free0 (url_css);
#line 130 "/run/build/Luna/src/views/BottomBar.vala"
																			url_css = _tmp79_;
#line 1020 "BottomBar.c"
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
#line 133 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp80_ = settings;
#line 133 "/run/build/Luna/src/views/BottomBar.vala"
	app_configs_settings_set_color (_tmp80_, color);
#line 135 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp81_ = css_provider;
#line 135 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp82_ = url_css;
#line 135 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_css_provider_load_from_resource (_tmp81_, _tmp82_);
#line 137 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp83_ = gdk_screen_get_default ();
#line 137 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp84_ = css_provider;
#line 137 "/run/build/Luna/src/views/BottomBar.vala"
	gtk_style_context_add_provider_for_screen (_tmp83_, (GtkStyleProvider*) _tmp84_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 87 "/run/build/Luna/src/views/BottomBar.vala"
	_g_free0 (url_css);
#line 87 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (css_provider);
#line 87 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (settings);
#line 1061 "BottomBar.c"
}


static void
app_views_bottom_bar_toggle_popup (AppViewsBottomBar* self,
                                   GtkPopover* popover)
{
#line 144 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (self != NULL);
#line 144 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (popover != NULL);
#line 145 "/run/build/Luna/src/views/BottomBar.vala"
	if (gtk_widget_is_visible ((GtkWidget*) popover)) {
#line 146 "/run/build/Luna/src/views/BottomBar.vala"
		gtk_widget_set_visible ((GtkWidget*) popover, FALSE);
#line 1077 "BottomBar.c"
	} else {
#line 148 "/run/build/Luna/src/views/BottomBar.vala"
		gtk_widget_set_visible ((GtkWidget*) popover, TRUE);
#line 1081 "BottomBar.c"
	}
}


GtkButton*
app_views_bottom_bar_get_menu_button (AppViewsBottomBar* self)
{
	GtkButton* result;
	GtkButton* _tmp0_;
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp0_ = self->priv->_menu_button;
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	result = _tmp0_;
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	return result;
#line 1099 "BottomBar.c"
}


static void
app_views_bottom_bar_set_menu_button (AppViewsBottomBar* self,
                                      GtkButton* value)
{
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (self != NULL);
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	if (app_views_bottom_bar_get_menu_button (self) != value) {
#line 1111 "BottomBar.c"
		GtkButton* _tmp0_;
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
		_g_object_unref0 (self->priv->_menu_button);
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
		self->priv->_menu_button = _tmp0_;
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
		g_object_notify_by_pspec ((GObject *) self, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY]);
#line 1121 "BottomBar.c"
	}
}


GtkButton*
app_views_bottom_bar_get_close_button (AppViewsBottomBar* self)
{
	GtkButton* result;
	GtkButton* _tmp0_;
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp0_ = self->priv->_close_button;
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	result = _tmp0_;
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	return result;
#line 1139 "BottomBar.c"
}


static void
app_views_bottom_bar_set_close_button (AppViewsBottomBar* self,
                                       GtkButton* value)
{
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (self != NULL);
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	if (app_views_bottom_bar_get_close_button (self) != value) {
#line 1151 "BottomBar.c"
		GtkButton* _tmp0_;
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
		_g_object_unref0 (self->priv->_close_button);
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
		self->priv->_close_button = _tmp0_;
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
		g_object_notify_by_pspec ((GObject *) self, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY]);
#line 1161 "BottomBar.c"
	}
}


GtkButton*
app_views_bottom_bar_get_today_button (AppViewsBottomBar* self)
{
	GtkButton* result;
	GtkButton* _tmp0_;
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	_tmp0_ = self->priv->_today_button;
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	result = _tmp0_;
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	return result;
#line 1179 "BottomBar.c"
}


static void
app_views_bottom_bar_set_today_button (AppViewsBottomBar* self,
                                       GtkButton* value)
{
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	g_return_if_fail (self != NULL);
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	if (app_views_bottom_bar_get_today_button (self) != value) {
#line 1191 "BottomBar.c"
		GtkButton* _tmp0_;
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
		_g_object_unref0 (self->priv->_today_button);
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
		self->priv->_today_button = _tmp0_;
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
		g_object_notify_by_pspec ((GObject *) self, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY]);
#line 1201 "BottomBar.c"
	}
}


static void
app_views_bottom_bar_class_init (AppViewsBottomBarClass * klass)
{
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_parent_class = g_type_class_peek_parent (klass);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	g_type_class_add_private (klass, sizeof (AppViewsBottomBarPrivate));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_app_views_bottom_bar_get_property;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_app_views_bottom_bar_set_property;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	G_OBJECT_CLASS (klass)->finalize = app_views_bottom_bar_finalize;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY] = g_param_spec_object ("menu-button", "menu-button", "menu-button", gtk_button_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY] = g_param_spec_object ("close-button", "close-button", "close-button", gtk_button_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY, app_views_bottom_bar_properties[APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY] = g_param_spec_object ("today-button", "today-button", "today-button", gtk_button_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_signals[APP_VIEWS_BOTTOM_BAR_TODAY_CLICKED_SIGNAL] = g_signal_new ("today-clicked", APP_VIEWS_TYPE_BOTTOM_BAR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	app_views_bottom_bar_signals[APP_VIEWS_BOTTOM_BAR_CLOSE_CLICKED_SIGNAL] = g_signal_new ("close-clicked", APP_VIEWS_TYPE_BOTTOM_BAR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1229 "BottomBar.c"
}


static void
app_views_bottom_bar_instance_init (AppViewsBottomBar * self)
{
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	self->priv = APP_VIEWS_BOTTOM_BAR_GET_PRIVATE (self);
#line 1238 "BottomBar.c"
}


static void
app_views_bottom_bar_finalize (GObject * obj)
{
	AppViewsBottomBar * self;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBar);
#line 32 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (self->priv->_menu_button);
#line 33 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (self->priv->_close_button);
#line 34 "/run/build/Luna/src/views/BottomBar.vala"
	_g_object_unref0 (self->priv->_today_button);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	G_OBJECT_CLASS (app_views_bottom_bar_parent_class)->finalize (obj);
#line 1256 "BottomBar.c"
}


GType
app_views_bottom_bar_get_type (void)
{
	static volatile gsize app_views_bottom_bar_type_id__volatile = 0;
	if (g_once_init_enter (&app_views_bottom_bar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppViewsBottomBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_views_bottom_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppViewsBottomBar), 0, (GInstanceInitFunc) app_views_bottom_bar_instance_init, NULL };
		GType app_views_bottom_bar_type_id;
		app_views_bottom_bar_type_id = g_type_register_static (gtk_box_get_type (), "AppViewsBottomBar", &g_define_type_info, 0);
		g_once_init_leave (&app_views_bottom_bar_type_id__volatile, app_views_bottom_bar_type_id);
	}
	return app_views_bottom_bar_type_id__volatile;
}


static void
_vala_app_views_bottom_bar_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec)
{
	AppViewsBottomBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBar);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	switch (property_id) {
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		g_value_set_object (value, app_views_bottom_bar_get_menu_button (self));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		g_value_set_object (value, app_views_bottom_bar_get_close_button (self));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		g_value_set_object (value, app_views_bottom_bar_get_today_button (self));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 1302 "BottomBar.c"
		default:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 1308 "BottomBar.c"
	}
}


static void
_vala_app_views_bottom_bar_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec)
{
	AppViewsBottomBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, APP_VIEWS_TYPE_BOTTOM_BAR, AppViewsBottomBar);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
	switch (property_id) {
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_MENU_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		app_views_bottom_bar_set_menu_button (self, g_value_get_object (value));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_CLOSE_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		app_views_bottom_bar_set_close_button (self, g_value_get_object (value));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		case APP_VIEWS_BOTTOM_BAR_TODAY_BUTTON_PROPERTY:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		app_views_bottom_bar_set_today_button (self, g_value_get_object (value));
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 1341 "BottomBar.c"
		default:
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/run/build/Luna/src/views/BottomBar.vala"
		break;
#line 1347 "BottomBar.c"
	}
}



