/* TwelveGridView.c generated by valac 0.40.11, the Vala compiler
 * generated from TwelveGridView.vala, do not modify */

/*
* Copyright (C) 2018  Carlos Lopez <calo_lrc@hotmail.com>
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
* 
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define APP_VIEWS_TYPE_TWELVE_GRID_VIEW (app_views_twelve_grid_view_get_type ())
#define APP_VIEWS_TWELVE_GRID_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_VIEWS_TYPE_TWELVE_GRID_VIEW, AppViewsTwelveGridView))
#define APP_VIEWS_TWELVE_GRID_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_VIEWS_TYPE_TWELVE_GRID_VIEW, AppViewsTwelveGridViewClass))
#define APP_VIEWS_IS_TWELVE_GRID_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_VIEWS_TYPE_TWELVE_GRID_VIEW))
#define APP_VIEWS_IS_TWELVE_GRID_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_VIEWS_TYPE_TWELVE_GRID_VIEW))
#define APP_VIEWS_TWELVE_GRID_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_VIEWS_TYPE_TWELVE_GRID_VIEW, AppViewsTwelveGridViewClass))

typedef struct _AppViewsTwelveGridView AppViewsTwelveGridView;
typedef struct _AppViewsTwelveGridViewClass AppViewsTwelveGridViewClass;
typedef struct _AppViewsTwelveGridViewPrivate AppViewsTwelveGridViewPrivate;
enum  {
	APP_VIEWS_TWELVE_GRID_VIEW_0_PROPERTY,
	APP_VIEWS_TWELVE_GRID_VIEW_NUM_PROPERTIES
};
static GParamSpec* app_views_twelve_grid_view_properties[APP_VIEWS_TWELVE_GRID_VIEW_NUM_PROPERTIES];
typedef struct _Block2Data Block2Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	APP_VIEWS_TWELVE_GRID_VIEW_OPTION_CLICK_SIGNAL,
	APP_VIEWS_TWELVE_GRID_VIEW_NUM_SIGNALS
};
static guint app_views_twelve_grid_view_signals[APP_VIEWS_TWELVE_GRID_VIEW_NUM_SIGNALS] = {0};

struct _AppViewsTwelveGridView {
	GtkGrid parent_instance;
	AppViewsTwelveGridViewPrivate * priv;
};

struct _AppViewsTwelveGridViewClass {
	GtkGridClass parent_class;
};

struct _AppViewsTwelveGridViewPrivate {
	GList* labels;
};

struct _Block2Data {
	int _ref_count_;
	AppViewsTwelveGridView* self;
	GtkButton* label_item;
};


static gpointer app_views_twelve_grid_view_parent_class = NULL;

GType app_views_twelve_grid_view_get_type (void) G_GNUC_CONST;
#define APP_VIEWS_TWELVE_GRID_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), APP_VIEWS_TYPE_TWELVE_GRID_VIEW, AppViewsTwelveGridViewPrivate))
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);
AppViewsTwelveGridView* app_views_twelve_grid_view_new (GList* items);
AppViewsTwelveGridView* app_views_twelve_grid_view_construct (GType object_type,
                                                              GList* items);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void ____lambda14_ (Block2Data* _data2_);
static void _____lambda14__gtk_button_clicked (GtkButton* _sender,
                                        gpointer self);
void app_views_twelve_grid_view_fill_grid (AppViewsTwelveGridView* self,
                                           GList* items);
static void g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                                  GValue * return_value,
                                                  guint n_param_values,
                                                  const GValue * param_values,
                                                  gpointer invocation_hint,
                                                  gpointer marshal_data);
static void app_views_twelve_grid_view_finalize (GObject * obj);


static void
_g_object_unref0_ (gpointer var)
{
#line 27 "/run/build/Luna/src/views/TwelveGridView.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 105 "TwelveGridView.c"
}


static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
#line 27 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
#line 114 "TwelveGridView.c"
}


static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
	return _data2_;
#line 125 "TwelveGridView.c"
}


static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 136 "TwelveGridView.c"
		AppViewsTwelveGridView* self;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		self = _data2_->self;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		_g_object_unref0 (_data2_->label_item);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		_g_object_unref0 (self);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		g_slice_free (Block2Data, _data2_);
#line 146 "TwelveGridView.c"
	}
}


static void
____lambda14_ (Block2Data* _data2_)
{
	AppViewsTwelveGridView* self;
	GtkButton* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GtkButton* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
#line 48 "/run/build/Luna/src/views/TwelveGridView.vala"
	self = _data2_->self;
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp0_ = _data2_->label_item;
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp1_ = gtk_widget_get_name ((GtkWidget*) _tmp0_);
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp2_ = _tmp1_;
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp3_ = _data2_->label_item;
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp4_ = gtk_button_get_label (_tmp3_);
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp5_ = _tmp4_;
#line 49 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_signal_emit (self, app_views_twelve_grid_view_signals[APP_VIEWS_TWELVE_GRID_VIEW_OPTION_CLICK_SIGNAL], 0, _tmp2_, _tmp5_);
#line 177 "TwelveGridView.c"
}


static void
_____lambda14__gtk_button_clicked (GtkButton* _sender,
                                   gpointer self)
{
#line 48 "/run/build/Luna/src/views/TwelveGridView.vala"
	____lambda14_ (self);
#line 187 "TwelveGridView.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 52 "/run/build/Luna/src/views/TwelveGridView.vala"
	return self ? g_object_ref (self) : NULL;
#line 196 "TwelveGridView.c"
}


AppViewsTwelveGridView*
app_views_twelve_grid_view_construct (GType object_type,
                                      GList* items)
{
	AppViewsTwelveGridView * self = NULL;
	gint name = 0;
	gint row = 0;
	gint column = 0;
#line 30 "/run/build/Luna/src/views/TwelveGridView.vala"
	self = (AppViewsTwelveGridView*) g_object_new (object_type, NULL);
#line 31 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_object_set ((GtkWidget*) self, "margin", 5, NULL);
#line 32 "/run/build/Luna/src/views/TwelveGridView.vala"
	gtk_grid_set_column_spacing ((GtkGrid*) self, 4);
#line 33 "/run/build/Luna/src/views/TwelveGridView.vala"
	gtk_grid_set_row_spacing ((GtkGrid*) self, 20);
#line 35 "/run/build/Luna/src/views/TwelveGridView.vala"
	name = 1;
#line 36 "/run/build/Luna/src/views/TwelveGridView.vala"
	row = 0;
#line 37 "/run/build/Luna/src/views/TwelveGridView.vala"
	column = 0;
#line 222 "TwelveGridView.c"
	{
		GList* item_collection = NULL;
		GList* item_it = NULL;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		item_collection = items;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
		for (item_it = item_collection; item_it != NULL; item_it = item_it->next) {
#line 230 "TwelveGridView.c"
			gchar* _tmp0_;
			gchar* item = NULL;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
			_tmp0_ = g_strdup ((const gchar*) item_it->data);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
			item = _tmp0_;
#line 237 "TwelveGridView.c"
			{
				Block2Data* _data2_;
				const gchar* _tmp1_;
				GtkButton* _tmp2_;
				GtkButton* _tmp3_;
				gint _tmp4_;
				gchar* _tmp5_;
				gchar* _tmp6_;
				GtkButton* _tmp7_;
				GtkButton* _tmp8_;
				GtkButton* _tmp9_;
				GtkButton* _tmp10_;
				GtkStyleContext* _tmp11_;
				GtkButton* _tmp12_;
				GtkStyleContext* _tmp13_;
				GtkButton* _tmp14_;
				GtkButton* _tmp15_;
				GtkButton* _tmp16_;
				GtkButton* _tmp17_;
				gint _tmp18_;
				gint _tmp19_;
				gint _tmp20_;
				gint _tmp21_;
				gint _tmp22_;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				_data2_ = g_slice_new0 (Block2Data);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				_data2_->_ref_count_ = 1;
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				_data2_->self = g_object_ref (self);
#line 39 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp1_ = item;
#line 39 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp2_ = (GtkButton*) gtk_button_new_with_label (_tmp1_);
#line 39 "/run/build/Luna/src/views/TwelveGridView.vala"
				g_object_ref_sink (_tmp2_);
#line 39 "/run/build/Luna/src/views/TwelveGridView.vala"
				_data2_->label_item = _tmp2_;
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp3_ = _data2_->label_item;
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp4_ = name;
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp5_ = g_strdup_printf ("%i", _tmp4_);
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp6_ = _tmp5_;
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_widget_set_name ((GtkWidget*) _tmp3_, _tmp6_);
#line 40 "/run/build/Luna/src/views/TwelveGridView.vala"
				_g_free0 (_tmp6_);
#line 41 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp7_ = _data2_->label_item;
#line 41 "/run/build/Luna/src/views/TwelveGridView.vala"
				g_object_set ((GtkWidget*) _tmp7_, "expand", TRUE, NULL);
#line 42 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp8_ = _data2_->label_item;
#line 42 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_widget_set_halign ((GtkWidget*) _tmp8_, GTK_ALIGN_FILL);
#line 43 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp9_ = _data2_->label_item;
#line 43 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_widget_set_valign ((GtkWidget*) _tmp9_, GTK_ALIGN_FILL);
#line 44 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp10_ = _data2_->label_item;
#line 44 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
#line 44 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_style_context_add_class (_tmp11_, "label-day");
#line 45 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp12_ = _data2_->label_item;
#line 45 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) _tmp12_);
#line 45 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_style_context_add_class (_tmp13_, "circle");
#line 48 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp14_ = _data2_->label_item;
#line 48 "/run/build/Luna/src/views/TwelveGridView.vala"
				g_signal_connect_data (_tmp14_, "clicked", (GCallback) _____lambda14__gtk_button_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 52 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp15_ = _data2_->label_item;
#line 52 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp16_ = _g_object_ref0 (_tmp15_);
#line 52 "/run/build/Luna/src/views/TwelveGridView.vala"
				self->priv->labels = g_list_append (self->priv->labels, _tmp16_);
#line 53 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp17_ = _data2_->label_item;
#line 53 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp18_ = column;
#line 53 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp19_ = row;
#line 53 "/run/build/Luna/src/views/TwelveGridView.vala"
				gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp17_, _tmp18_, _tmp19_, 1, 1);
#line 54 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp20_ = name;
#line 54 "/run/build/Luna/src/views/TwelveGridView.vala"
				name = _tmp20_ + 1;
#line 55 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp21_ = column;
#line 55 "/run/build/Luna/src/views/TwelveGridView.vala"
				column = _tmp21_ + 1;
#line 56 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp22_ = column;
#line 56 "/run/build/Luna/src/views/TwelveGridView.vala"
				if ((_tmp22_ % 4) == 0) {
#line 342 "TwelveGridView.c"
					gint _tmp23_;
#line 57 "/run/build/Luna/src/views/TwelveGridView.vala"
					column = 0;
#line 58 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp23_ = row;
#line 58 "/run/build/Luna/src/views/TwelveGridView.vala"
					row = _tmp23_ + 1;
#line 350 "TwelveGridView.c"
				}
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				_g_free0 (item);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				block2_data_unref (_data2_);
#line 38 "/run/build/Luna/src/views/TwelveGridView.vala"
				_data2_ = NULL;
#line 358 "TwelveGridView.c"
			}
		}
	}
#line 30 "/run/build/Luna/src/views/TwelveGridView.vala"
	return self;
#line 364 "TwelveGridView.c"
}


AppViewsTwelveGridView*
app_views_twelve_grid_view_new (GList* items)
{
#line 30 "/run/build/Luna/src/views/TwelveGridView.vala"
	return app_views_twelve_grid_view_construct (APP_VIEWS_TYPE_TWELVE_GRID_VIEW, items);
#line 373 "TwelveGridView.c"
}


void
app_views_twelve_grid_view_fill_grid (AppViewsTwelveGridView* self,
                                      GList* items)
{
	guint elements = 0U;
	GList* _tmp0_;
	guint new_elements = 0U;
	guint _tmp1_;
	guint _tmp2_;
#line 63 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_return_if_fail (self != NULL);
#line 64 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp0_ = self->priv->labels;
#line 64 "/run/build/Luna/src/views/TwelveGridView.vala"
	elements = g_list_length (_tmp0_);
#line 65 "/run/build/Luna/src/views/TwelveGridView.vala"
	new_elements = g_list_length (items);
#line 66 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp1_ = elements;
#line 66 "/run/build/Luna/src/views/TwelveGridView.vala"
	_tmp2_ = new_elements;
#line 66 "/run/build/Luna/src/views/TwelveGridView.vala"
	if (_tmp1_ == _tmp2_) {
#line 400 "TwelveGridView.c"
		{
			gint i = 0;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
			i = 0;
#line 405 "TwelveGridView.c"
			{
				gboolean _tmp3_ = FALSE;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
				_tmp3_ = TRUE;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
				while (TRUE) {
#line 412 "TwelveGridView.c"
					gint _tmp5_;
					guint _tmp6_;
					GtkButton* label = NULL;
					GList* _tmp7_;
					gint _tmp8_;
					gconstpointer _tmp9_;
					GtkButton* _tmp10_;
					GtkButton* _tmp11_;
					gint _tmp12_;
					gconstpointer _tmp13_;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					if (!_tmp3_) {
#line 425 "TwelveGridView.c"
						gint _tmp4_;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
						_tmp4_ = i;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
						i = _tmp4_ + 1;
#line 431 "TwelveGridView.c"
					}
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp3_ = FALSE;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp5_ = i;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp6_ = elements;
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					if (!(((guint) _tmp5_) < _tmp6_)) {
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
						break;
#line 443 "TwelveGridView.c"
					}
#line 68 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp7_ = self->priv->labels;
#line 68 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp8_ = i;
#line 68 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp9_ = g_list_nth_data (_tmp7_, (guint) _tmp8_);
#line 68 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp10_ = _g_object_ref0 ((GtkButton*) _tmp9_);
#line 68 "/run/build/Luna/src/views/TwelveGridView.vala"
					label = _tmp10_;
#line 69 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp11_ = label;
#line 69 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp12_ = i;
#line 69 "/run/build/Luna/src/views/TwelveGridView.vala"
					_tmp13_ = g_list_nth_data (items, (guint) _tmp12_);
#line 69 "/run/build/Luna/src/views/TwelveGridView.vala"
					gtk_button_set_label (_tmp11_, (const gchar*) _tmp13_);
#line 67 "/run/build/Luna/src/views/TwelveGridView.vala"
					_g_object_unref0 (label);
#line 465 "TwelveGridView.c"
				}
			}
		}
	}
}


static void
g_cclosure_user_marshal_VOID__STRING_STRING (GClosure * closure,
                                             GValue * return_value,
                                             guint n_param_values,
                                             const GValue * param_values,
                                             gpointer invocation_hint,
                                             gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__STRING_STRING) (gpointer data1, const char* arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_return_if_fail (n_param_values == 3);
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
		data1 = closure->data;
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
		data2 = param_values->data[0].v_pointer;
#line 495 "TwelveGridView.c"
	} else {
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
		data1 = param_values->data[0].v_pointer;
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
		data2 = closure->data;
#line 501 "TwelveGridView.c"
	}
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	callback = (GMarshalFunc_VOID__STRING_STRING) (marshal_data ? marshal_data : cc->callback);
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	callback (data1, g_value_get_string (param_values + 1), g_value_get_string (param_values + 2), data2);
#line 507 "TwelveGridView.c"
}


static void
app_views_twelve_grid_view_class_init (AppViewsTwelveGridViewClass * klass)
{
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	app_views_twelve_grid_view_parent_class = g_type_class_peek_parent (klass);
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	g_type_class_add_private (klass, sizeof (AppViewsTwelveGridViewPrivate));
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	G_OBJECT_CLASS (klass)->finalize = app_views_twelve_grid_view_finalize;
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	app_views_twelve_grid_view_signals[APP_VIEWS_TWELVE_GRID_VIEW_OPTION_CLICK_SIGNAL] = g_signal_new ("option-click", APP_VIEWS_TYPE_TWELVE_GRID_VIEW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_STRING, G_TYPE_NONE, 2, G_TYPE_STRING, G_TYPE_STRING);
#line 522 "TwelveGridView.c"
}


static void
app_views_twelve_grid_view_instance_init (AppViewsTwelveGridView * self)
{
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	self->priv = APP_VIEWS_TWELVE_GRID_VIEW_GET_PRIVATE (self);
#line 531 "TwelveGridView.c"
}


static void
app_views_twelve_grid_view_finalize (GObject * obj)
{
	AppViewsTwelveGridView * self;
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, APP_VIEWS_TYPE_TWELVE_GRID_VIEW, AppViewsTwelveGridView);
#line 27 "/run/build/Luna/src/views/TwelveGridView.vala"
	(self->priv->labels == NULL) ? NULL : (self->priv->labels = (_g_list_free__g_object_unref0_ (self->priv->labels), NULL));
#line 26 "/run/build/Luna/src/views/TwelveGridView.vala"
	G_OBJECT_CLASS (app_views_twelve_grid_view_parent_class)->finalize (obj);
#line 545 "TwelveGridView.c"
}


/**
     * The {@code CalendarView} class. Show a grid 12x12 for months and years
     *
     * @since 1.0.0
     */
GType
app_views_twelve_grid_view_get_type (void)
{
	static volatile gsize app_views_twelve_grid_view_type_id__volatile = 0;
	if (g_once_init_enter (&app_views_twelve_grid_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppViewsTwelveGridViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_views_twelve_grid_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppViewsTwelveGridView), 0, (GInstanceInitFunc) app_views_twelve_grid_view_instance_init, NULL };
		GType app_views_twelve_grid_view_type_id;
		app_views_twelve_grid_view_type_id = g_type_register_static (gtk_grid_get_type (), "AppViewsTwelveGridView", &g_define_type_info, 0);
		g_once_init_leave (&app_views_twelve_grid_view_type_id__volatile, app_views_twelve_grid_view_type_id);
	}
	return app_views_twelve_grid_view_type_id__volatile;
}



